// AUTO-GENERATED by scripts/generate-curriculum.mjs — nie edytuj ręcznie.
// a2-05-03 · Większy czy tańszy?
// Źródło: curriculum/hr-a2/lexodromia_hr_A2_curriculum.csv (sha256 c31e8911b38176e3…) + didactics.json
import type { GeneratedLesson } from "../../../types";

export const LESSON: GeneratedLesson = {
  content: {
    "lessonId": "a2-05-03",
    "vocabulary": [
      {
        "target": "veći",
        "source": "większy",
        "lemma": "velik",
        "partOfSpeech": "adjective",
        "recordId": "A2-0556",
        "review": {
          "itemType": "WORD",
          "itemId": "pl-hr:894"
        },
        "accepted": [
          "veći"
        ],
        "audioSrc": "/audio/hr/a2/module-05/veci.mp3"
      },
      {
        "target": "manji",
        "source": "mniejszy",
        "lemma": "malen",
        "partOfSpeech": "adjective",
        "recordId": "A2-0557",
        "review": {
          "itemType": "WORD",
          "itemId": "pl-hr:895"
        },
        "accepted": [
          "manji"
        ],
        "audioSrc": "/audio/hr/a2/module-05/manji.mp3"
      },
      {
        "target": "jeftiniji",
        "source": "tańszy",
        "lemma": "jeftin",
        "partOfSpeech": "adjective",
        "recordId": "A2-0558",
        "review": {
          "itemType": "PHRASE",
          "itemId": "pl-hr:phrase:jeftiniji"
        },
        "accepted": [
          "jeftiniji"
        ],
        "audioSrc": "/audio/hr/a2/module-05/jeftiniji.mp3"
      },
      {
        "target": "skuplji",
        "source": "droższy",
        "lemma": "skup",
        "partOfSpeech": "adjective",
        "recordId": "A2-0559",
        "review": {
          "itemType": "PHRASE",
          "itemId": "pl-hr:phrase:skuplji"
        },
        "accepted": [
          "skuplji"
        ],
        "audioSrc": "/audio/hr/a2/module-05/skuplji.mp3"
      },
      {
        "target": "kraći",
        "source": "krótszy",
        "lemma": "kratak",
        "partOfSpeech": "adjective",
        "recordId": "A2-0560",
        "review": {
          "itemType": "PHRASE",
          "itemId": "pl-hr:phrase:kraći"
        },
        "accepted": [
          "kraći"
        ],
        "audioSrc": "/audio/hr/a2/module-05/kraci.mp3"
      },
      {
        "target": "duži",
        "source": "dłuższy",
        "lemma": "dug",
        "partOfSpeech": "adjective",
        "recordId": "A2-0561",
        "review": {
          "itemType": "PHRASE",
          "itemId": "pl-hr:phrase:duži"
        },
        "accepted": [
          "duži"
        ],
        "audioSrc": "/audio/hr/a2/module-05/duzi.mp3"
      },
      {
        "target": "onaj",
        "source": "tamten",
        "lemma": "onaj",
        "partOfSpeech": "pronoun",
        "recordId": "A2-0562",
        "review": {
          "itemType": "WORD",
          "itemId": "pl-hr:95"
        },
        "accepted": [
          "onaj"
        ],
        "audioSrc": "/audio/hr/a2/module-05/onaj.mp3"
      },
      {
        "target": "popust",
        "source": "zniżka / rabat",
        "lemma": "popust",
        "partOfSpeech": "noun",
        "recordId": "A2-0563",
        "review": {
          "itemType": "WORD",
          "itemId": "pl-hr:556"
        },
        "accepted": [
          "popust"
        ],
        "audioSrc": "/audio/hr/a2/module-05/popust.mp3"
      },
      {
        "target": "rasprodaja",
        "source": "wyprzedaż",
        "lemma": "rasprodaja",
        "partOfSpeech": "noun",
        "recordId": "A2-0564",
        "review": {
          "itemType": "PHRASE",
          "itemId": "pl-hr:phrase:rasprodaja"
        },
        "accepted": [
          "rasprodaja"
        ],
        "optional": true,
        "audioSrc": "/audio/hr/a2/module-05/rasprodaja.mp3"
      },
      {
        "target": "najjeftiniji",
        "source": "najtańszy",
        "lemma": "jeftin",
        "partOfSpeech": "adjective",
        "recordId": "A2-0565",
        "review": {
          "itemType": "PHRASE",
          "itemId": "pl-hr:phrase:najjeftiniji"
        },
        "accepted": [
          "najjeftiniji"
        ],
        "optional": true,
        "audioSrc": "/audio/hr/a2/module-05/najjeftiniji.mp3"
      },
      {
        "target": "isti",
        "source": "taki sam",
        "lemma": "isti",
        "partOfSpeech": "adjective",
        "recordId": "A2-0566",
        "review": {
          "itemType": "WORD",
          "itemId": "pl-hr:896"
        },
        "accepted": [
          "isti"
        ],
        "optional": true,
        "audioSrc": "/audio/hr/a2/module-05/isti.mp3"
      }
    ],
    "steps": [
      {
        "id": "intro",
        "stage": "intro",
        "type": "intro",
        "title": "Większy czy tańszy?",
        "body": "Po tej lekcji będziesz umieć porównać rzeczy w sklepie i poprosić o inny rozmiar.",
        "goalsTitle": "Powiesz między innymi",
        "goals": [
          {
            "target": "Imate li veći broj?",
            "source": "Ma Pani większy rozmiar?",
            "audioSrc": "/audio/hr/a2/module-05/imate-li-veci-broj.mp3"
          },
          {
            "target": "Ova jakna je jeftinija od one.",
            "source": "Ta kurtka jest tańsza od tamtej.",
            "audioSrc": "/audio/hr/a2/module-05/ova-jakna-je-jeftinija-od-one.mp3"
          },
          {
            "target": "Crne cipele su skuplje nego bijele.",
            "source": "Czarne buty są droższe niż białe.",
            "audioSrc": "/audio/hr/a2/module-05/crne-cipele-su-skuplje-nego-bijele.mp3"
          }
        ]
      },
      {
        "id": "word-1",
        "stage": "words",
        "type": "word",
        "target": "veći",
        "source": "większy",
        "partOfSpeech": "przymiotnik",
        "example": {
          "target": "Imate li veći broj?",
          "source": "Ma Pani większy rozmiar?",
          "audioSrc": "/audio/hr/a2/module-05/imate-li-veci-broj.mp3"
        },
        "audioSrc": "/audio/hr/a2/module-05/veci.mp3"
      },
      {
        "id": "word-2",
        "stage": "words",
        "type": "word",
        "target": "manji",
        "source": "mniejszy",
        "partOfSpeech": "przymiotnik",
        "example": {
          "target": "Trebam manju veličinu.",
          "source": "Potrzebuję mniejszego rozmiaru.",
          "audioSrc": "/audio/hr/a2/module-05/trebam-manju-velicinu.mp3"
        },
        "audioSrc": "/audio/hr/a2/module-05/manji.mp3"
      },
      {
        "id": "word-3",
        "stage": "words",
        "type": "word",
        "target": "jeftiniji",
        "source": "tańszy",
        "partOfSpeech": "przymiotnik",
        "example": {
          "target": "Ova jakna je jeftinija od one.",
          "source": "Ta kurtka jest tańsza od tamtej.",
          "audioSrc": "/audio/hr/a2/module-05/ova-jakna-je-jeftinija-od-one.mp3"
        },
        "audioSrc": "/audio/hr/a2/module-05/jeftiniji.mp3"
      },
      {
        "id": "check-1",
        "stage": "words",
        "type": "choice",
        "instruction": "Co znaczy to słowo?",
        "prompt": "jeftiniji",
        "options": [
          "krótszy",
          "tamten",
          "tańszy"
        ],
        "correctIndex": 2,
        "targetText": "prompt",
        "promptAudioSrc": "/audio/hr/a2/module-05/jeftiniji.mp3"
      },
      {
        "id": "word-4",
        "stage": "words",
        "type": "word",
        "target": "skuplji",
        "source": "droższy",
        "partOfSpeech": "przymiotnik",
        "example": {
          "target": "Crne cipele su skuplje nego bijele.",
          "source": "Czarne buty są droższe niż białe.",
          "audioSrc": "/audio/hr/a2/module-05/crne-cipele-su-skuplje-nego-bijele.mp3"
        },
        "audioSrc": "/audio/hr/a2/module-05/skuplji.mp3"
      },
      {
        "id": "word-5",
        "stage": "words",
        "type": "word",
        "target": "kraći",
        "source": "krótszy",
        "partOfSpeech": "przymiotnik",
        "example": {
          "target": "Ta haljina je kraća.",
          "source": "Ta sukienka jest krótsza.",
          "audioSrc": "/audio/hr/a2/module-05/ta-haljina-je-kraca.mp3"
        },
        "audioSrc": "/audio/hr/a2/module-05/kraci.mp3"
      },
      {
        "id": "word-6",
        "stage": "words",
        "type": "word",
        "target": "duži",
        "source": "dłuższy",
        "partOfSpeech": "przymiotnik",
        "example": {
          "target": "Ove hlače su duže.",
          "source": "Te spodnie są dłuższe.",
          "audioSrc": "/audio/hr/a2/module-05/ove-hlace-su-duze.mp3"
        },
        "audioSrc": "/audio/hr/a2/module-05/duzi.mp3"
      },
      {
        "id": "check-2",
        "stage": "words",
        "type": "choice",
        "instruction": "Jak powiesz to po chorwacku?",
        "prompt": "droższy",
        "options": [
          "skuplji",
          "veći",
          "manji"
        ],
        "correctIndex": 0,
        "targetText": "options",
        "answerAudioSrc": "/audio/hr/a2/module-05/skuplji.mp3"
      },
      {
        "id": "word-7",
        "stage": "words",
        "type": "word",
        "target": "onaj",
        "source": "tamten",
        "partOfSpeech": "zaimek",
        "example": {
          "target": "Sviđa mi se onaj kaput.",
          "source": "Podoba mi się tamten płaszcz.",
          "audioSrc": "/audio/hr/a2/module-05/svidja-mi-se-onaj-kaput.mp3"
        },
        "audioSrc": "/audio/hr/a2/module-05/onaj.mp3"
      },
      {
        "id": "word-8",
        "stage": "words",
        "type": "word",
        "target": "popust",
        "source": "zniżka / rabat",
        "partOfSpeech": "rzeczownik",
        "example": {
          "target": "Ima li popusta?",
          "source": "Czy jest jakaś zniżka?",
          "audioSrc": "/audio/hr/a2/module-05/ima-li-popusta.mp3"
        },
        "audioSrc": "/audio/hr/a2/module-05/popust.mp3"
      },
      {
        "id": "check-3",
        "stage": "words",
        "type": "choice",
        "instruction": "Co znaczy to słowo?",
        "prompt": "popust",
        "options": [
          "większy",
          "zniżka / rabat",
          "krótszy"
        ],
        "correctIndex": 1,
        "targetText": "prompt",
        "promptAudioSrc": "/audio/hr/a2/module-05/popust.mp3"
      },
      {
        "id": "more-words",
        "stage": "words",
        "type": "vocabList",
        "title": "Więcej przydatnych słów",
        "note": "Słowa dodatkowe: odsłuchaj i powtórz na głos. Nie musisz znać ich na pamięć — do powtórek trafiają słowa z kart.",
        "items": [
          {
            "target": "rasprodaja",
            "source": "wyprzedaż",
            "partOfSpeech": "rzeczownik",
            "audioSrc": "/audio/hr/a2/module-05/rasprodaja.mp3"
          },
          {
            "target": "najjeftiniji",
            "source": "najtańszy",
            "partOfSpeech": "przymiotnik",
            "audioSrc": "/audio/hr/a2/module-05/najjeftiniji.mp3"
          },
          {
            "target": "isti",
            "source": "taki sam",
            "partOfSpeech": "przymiotnik",
            "audioSrc": "/audio/hr/a2/module-05/isti.mp3"
          }
        ]
      },
      {
        "id": "check-more",
        "stage": "words",
        "type": "choice",
        "instruction": "Co znaczy to słowo?",
        "prompt": "isti",
        "options": [
          "wyprzedaż",
          "najtańszy",
          "taki sam"
        ],
        "correctIndex": 2,
        "targetText": "prompt",
        "optional": true,
        "promptAudioSrc": "/audio/hr/a2/module-05/isti.mp3"
      },
      {
        "id": "examples",
        "stage": "words",
        "type": "structure",
        "title": "Nowe słowa w zdaniach",
        "explanation": "Posłuchaj, jak nowe słowa brzmią w krótkich, codziennych zdaniach.",
        "examples": [
          {
            "target": "Danas je velika rasprodaja.",
            "source": "Dziś jest duża wyprzedaż.",
            "audioSrc": "/audio/hr/a2/module-05/danas-je-velika-rasprodaja.mp3"
          },
          {
            "target": "Ovo je najjeftinija jakna.",
            "source": "To jest najtańsza kurtka.",
            "audioSrc": "/audio/hr/a2/module-05/ovo-je-najjeftinija-jakna.mp3"
          },
          {
            "target": "Imate li istu majicu u crnoj boji?",
            "source": "Ma Pani taką samą koszulkę w czarnym kolorze?",
            "audioSrc": "/audio/hr/a2/module-05/imate-li-istu-majicu-u-crnoj-boji.mp3"
          }
        ]
      },
      {
        "id": "structure",
        "stage": "structure",
        "type": "structure",
        "title": "Jeftinija od one",
        "explanation": "Stopień wyższy przymiotnika: -iji / -ji: jeftin → jeftiniji, skup → skuplji, dug → duži, kratak → kraći; nieregularnie velik → veći, malen → manji. Zgadza się z rzeczownikiem: jeftinija jakna, skuplje cipele. „Niż”: od + dopełniacz (jeftinija od one) albo nego (skuplje nego bijele). Najwyższy: naj- + stopień wyższy: najjeftiniji.",
        "table": [
          {
            "label": "przymiotnik → stopień wyższy",
            "rows": [
              {
                "base": "velik",
                "form": "veći",
                "meaning": "większy",
                "audioSrc": "/audio/hr/a2/module-05/veci.mp3"
              },
              {
                "base": "malen",
                "form": "manji",
                "meaning": "mniejszy",
                "audioSrc": "/audio/hr/a2/module-05/manji.mp3"
              },
              {
                "base": "jeftin",
                "form": "jeftiniji",
                "meaning": "tańszy",
                "audioSrc": "/audio/hr/a2/module-05/jeftiniji.mp3"
              },
              {
                "base": "skup",
                "form": "skuplji",
                "meaning": "droższy",
                "audioSrc": "/audio/hr/a2/module-05/skuplji.mp3"
              },
              {
                "base": "dug",
                "form": "duži",
                "meaning": "dłuższy",
                "audioSrc": "/audio/hr/a2/module-05/duzi.mp3"
              },
              {
                "base": "kratak",
                "form": "kraći",
                "meaning": "krótszy",
                "audioSrc": "/audio/hr/a2/module-05/kraci.mp3"
              }
            ]
          },
          {
            "label": "ovaj · taj · onaj",
            "rows": [
              {
                "base": "tu, przy mnie",
                "form": "ovaj kaput",
                "meaning": "ten płaszcz",
                "audioSrc": "/audio/hr/a2/module-05/ovaj-kaput.mp3"
              },
              {
                "base": "przy tobie",
                "form": "taj kaput",
                "meaning": "ten płaszcz (twój)",
                "audioSrc": "/audio/hr/a2/module-05/taj-kaput.mp3"
              },
              {
                "base": "daleko",
                "form": "onaj kaput",
                "meaning": "tamten płaszcz",
                "audioSrc": "/audio/hr/a2/module-05/onaj-kaput.mp3"
              }
            ]
          }
        ],
        "examples": [
          {
            "target": "Ova jakna je jeftinija od one.",
            "source": "Ta kurtka jest tańsza od tamtej.",
            "audioSrc": "/audio/hr/a2/module-05/ova-jakna-je-jeftinija-od-one.mp3"
          },
          {
            "target": "Crne cipele su skuplje nego bijele.",
            "source": "Czarne buty są droższe niż białe.",
            "audioSrc": "/audio/hr/a2/module-05/crne-cipele-su-skuplje-nego-bijele.mp3"
          },
          {
            "target": "Imate li veći broj?",
            "source": "Ma Pani większy rozmiar?",
            "audioSrc": "/audio/hr/a2/module-05/imate-li-veci-broj.mp3"
          },
          {
            "target": "Sviđa mi se onaj kaput.",
            "source": "Podoba mi się tamten płaszcz.",
            "audioSrc": "/audio/hr/a2/module-05/svidja-mi-se-onaj-kaput.mp3"
          }
        ],
        "note": "Rozmiar butów: veći / manji broj; rozmiar ubrania: veća / manja veličina (veličina jest rodzaju żeńskiego)."
      },
      {
        "id": "gap",
        "stage": "structure",
        "type": "gap",
        "instruction": "Uzupełnij lukę.",
        "before": "Ova jakna je",
        "after": "od one.",
        "accepted": [
          "jeftinija"
        ],
        "translation": "Ta kurtka jest tańsza od tamtej.",
        "rule": "Jeftinija od one — Stopień wyższy przymiotnika: -iji / -ji: jeftin → jeftiniji, skup → skuplji, dug → duži, kratak → kraći; nieregularnie velik → veći, malen → manji.",
        "answerAudioSrc": "/audio/hr/a2/module-05/ova-jakna-je-jeftinija-od-one.mp3"
      },
      {
        "id": "comprehend",
        "stage": "practice",
        "type": "choice",
        "instruction": "Co znaczy to zdanie?",
        "prompt": "Crne cipele su skuplje nego bijele.",
        "options": [
          "Ma Pani większy rozmiar?",
          "Ta kurtka jest tańsza od tamtej.",
          "Czarne buty są droższe niż białe."
        ],
        "correctIndex": 2,
        "targetText": "prompt",
        "promptAudioSrc": "/audio/hr/a2/module-05/crne-cipele-su-skuplje-nego-bijele.mp3"
      },
      {
        "id": "choice-1",
        "stage": "practice",
        "type": "choice",
        "instruction": "Wybierz poprawne zdanie.",
        "prompt": "Te buty są droższe.",
        "options": [
          "Ove cipele su skupije.",
          "Ove cipele su skuplje.",
          "Ove cipele su više skupe."
        ],
        "correctIndex": 1,
        "explanation": "skup → skuplji; cipele (lm. ż.) → skuplje.",
        "targetText": "options",
        "answerAudioSrc": "/audio/hr/a2/module-05/ove-cipele-su-skuplje.mp3"
      },
      {
        "id": "order",
        "stage": "practice",
        "type": "order",
        "instruction": "Ułóż zdanie.",
        "translation": "Podoba mi się tamten płaszcz.",
        "tokens": [
          "se",
          "sviđa",
          "kaput",
          "onaj",
          "mi"
        ],
        "accepted": [
          "Sviđa mi se onaj kaput."
        ],
        "rule": "Krótkie słowa (sam, si, je, se, ću, li…) stoją zwykle na drugim miejscu w zdaniu — zaraz po pierwszym słowie albo zwrocie.",
        "answerAudioSrc": "/audio/hr/a2/module-05/svidja-mi-se-onaj-kaput.mp3"
      },
      {
        "id": "translate-1",
        "stage": "practice",
        "type": "translate",
        "instruction": "Przetłumacz na chorwacki.",
        "prompt": "Ma Pani większy rozmiar?",
        "accepted": [
          "Imate li veći broj?"
        ],
        "answerAudioSrc": "/audio/hr/a2/module-05/imate-li-veci-broj.mp3"
      },
      {
        "id": "translate-2",
        "stage": "practice",
        "type": "translate",
        "instruction": "Przetłumacz na chorwacki.",
        "prompt": "Potrzebuję mniejszego rozmiaru.",
        "accepted": [
          "Trebam manju veličinu.",
          "Ja trebam manju veličinu."
        ],
        "answerAudioSrc": "/audio/hr/a2/module-05/trebam-manju-velicinu.mp3"
      },
      {
        "id": "translate-more",
        "stage": "practice",
        "type": "translate",
        "instruction": "Przetłumacz na chorwacki.",
        "prompt": "Dziś jest duża wyprzedaż.",
        "accepted": [
          "Danas je velika rasprodaja."
        ],
        "optional": true,
        "answerAudioSrc": "/audio/hr/a2/module-05/danas-je-velika-rasprodaja.mp3"
      },
      {
        "id": "listening",
        "stage": "dialog",
        "type": "listening",
        "instruction": "Posłuchaj dialogu i odpowiedz na pytanie.",
        "title": "Który płaszcz?",
        "lines": [
          {
            "speaker": "Ana",
            "text": "Marko, koji ti se kaput više sviđa?",
            "translation": "Marko, który płaszcz bardziej ci się podoba?",
            "audio": "/audio/listening/hr-a2/a2-novi-kaput/01-ana.mp3"
          },
          {
            "speaker": "Marko",
            "text": "Sivi je elegantniji, ali plavi je topliji.",
            "translation": "Szary jest bardziej elegancki, ale niebieski jest cieplejszy.",
            "audio": "/audio/listening/hr-a2/a2-novi-kaput/02-marko.mp3"
          },
          {
            "speaker": "Ana",
            "text": "Plavi je i jeftiniji, košta osamdeset eura.",
            "translation": "Niebieski jest też tańszy, kosztuje osiemdziesiąt euro.",
            "audio": "/audio/listening/hr-a2/a2-novi-kaput/03-ana.mp3"
          },
          {
            "speaker": "Marko",
            "text": "A koliko košta sivi?",
            "translation": "A ile kosztuje szary?",
            "audio": "/audio/listening/hr-a2/a2-novi-kaput/04-marko.mp3"
          },
          {
            "speaker": "Ana",
            "text": "Sto dvadeset. To mi je previše.",
            "translation": "Sto dwadzieścia. To dla mnie za dużo.",
            "audio": "/audio/listening/hr-a2/a2-novi-kaput/05-ana.mp3"
          },
          {
            "speaker": "Marko",
            "text": "Onda uzmi plavi. I meni se više sviđa.",
            "translation": "To weź niebieski. Mnie też bardziej się podoba.",
            "audio": "/audio/listening/hr-a2/a2-novi-kaput/06-marko.mp3"
          }
        ],
        "questions": [
          {
            "prompt": "Dlaczego Ana weźmie niebieski płaszcz?",
            "options": [
              "Jest tańszy i cieplejszy",
              "Jest bardziej elegancki",
              "Szary jest za mały"
            ],
            "correctIndex": 0
          }
        ]
      },
      {
        "id": "model",
        "stage": "dialog",
        "type": "listen",
        "title": "Który płaszcz?",
        "lines": [
          {
            "speaker": "Marko",
            "text": "Koji kaput ti se više sviđa, ovaj ili onaj?",
            "translation": "Który płaszcz bardziej ci się podoba, ten czy tamten?",
            "audioSrc": "/audio/hr/a2/module-05/koji-kaput-ti-se-vise-svidja-ovaj-ili-onaj-m.mp3"
          },
          {
            "speaker": "Ana",
            "text": "Onaj sivi je ljepši, ali je skuplji.",
            "translation": "Tamten szary jest ładniejszy, ale droższy.",
            "audioSrc": "/audio/hr/a2/module-05/onaj-sivi-je-ljepsi-ali-je-skuplji.mp3"
          },
          {
            "speaker": "Marko",
            "text": "Ovaj je jeftiniji i topliji.",
            "translation": "Ten jest tańszy i cieplejszy.",
            "audioSrc": "/audio/hr/a2/module-05/ovaj-je-jeftiniji-i-topliji-m.mp3"
          },
          {
            "speaker": "Ana",
            "text": "Imaju li ga u manjoj veličini?",
            "translation": "Mają go w mniejszym rozmiarze?",
            "audioSrc": "/audio/hr/a2/module-05/imaju-li-ga-u-manjoj-velicini.mp3"
          },
          {
            "speaker": "Marko",
            "text": "Pitat ću prodavača. Danas ima i popust!",
            "translation": "Zapytam sprzedawcę. Dziś jest też zniżka!",
            "audioSrc": "/audio/hr/a2/module-05/pitat-cu-prodavaca-danas-ima-i-popust-m.mp3"
          }
        ]
      },
      {
        "id": "dialog",
        "stage": "dialog",
        "type": "dialog",
        "title": "Inny rozmiar",
        "turns": [
          {
            "kind": "line",
            "line": {
              "speaker": "Prodavač",
              "text": "Kako vam pristaju cipele?",
              "translation": "Jak pasują buty?",
              "audioSrc": "/audio/hr/a2/module-05/kako-vam-pristaju-cipele-m.mp3"
            }
          },
          {
            "kind": "reply",
            "prompt": "Powiedz, że są za małe albo za duże, i poproś o inny rozmiar.",
            "accepted": [
              "Imate li veći broj?",
              "Male su. Imate li veći broj?"
            ],
            "pattern": "^(?:(?:bok|zdravo|hej|dobar dan|dobro jutro|dobra večer|oprostite|hvala(?: lijepa| vam)?|prodavač) )*(?:((male|velike|uske|široke|premale|prevelike) su( mi)? )?(imate li|trebam|molim)( jedan| jednu)? ((veći|manji|drugi) broj|(veću|manju|drugu) veličinu)|(male|velike|uske|premale|prevelike) su( mi)?)(?: (?:hvala(?: lijepa| vam)?|a ti|a vi|molim(?: vas)?|prodavač))*$",
            "suggestion": "Imate li veći broj?",
            "suggestionAudioSrc": "/audio/hr/a2/module-05/imate-li-veci-broj.mp3"
          },
          {
            "kind": "line",
            "line": {
              "speaker": "Prodavač",
              "text": "Izvolite, ovo je broj četrdeset dva.",
              "translation": "Proszę, to jest rozmiar czterdzieści dwa.",
              "audioSrc": "/audio/hr/a2/module-05/izvolite-ovo-je-broj-cetrdeset-dva-m.mp3"
            }
          },
          {
            "kind": "reply",
            "prompt": "Zapytaj o cenę albo o zniżkę.",
            "accepted": [
              "Koliko koštaju?",
              "Ima li popusta?"
            ],
            "pattern": "^(?:(?:bok|zdravo|hej|dobar dan|dobro jutro|dobra večer|oprostite|hvala(?: lijepa| vam)?|prodavač) )*(?:(koliko (košta|koštaju|je)( to| ovo| ovaj| ove)?|ima li (popusta|neki popust)|imate li (popust|neki popust)|je li (to|ovo) na (popustu|akciji)))(?: (?:hvala(?: lijepa| vam)?|a ti|a vi|molim(?: vas)?|prodavač))*$",
            "suggestion": "Koliko koštaju?",
            "suggestionAudioSrc": "/audio/hr/a2/module-05/koliko-kostaju.mp3"
          },
          {
            "kind": "line",
            "line": {
              "speaker": "Prodavač",
              "text": "Sto eura, ali danas je dvadeset posto popusta.",
              "translation": "Sto euro, ale dziś jest dwadzieścia procent zniżki.",
              "audioSrc": "/audio/hr/a2/module-05/sto-eura-ali-danas-je-dvadeset-posto-popusta-m.mp3"
            }
          },
          {
            "kind": "reply",
            "prompt": "Zdecyduj: bierzesz je albo nie.",
            "accepted": [
              "Uzet ću ih.",
              "Hvala, ali preskupe su."
            ],
            "pattern": "^(?:(?:bok|zdravo|hej|dobar dan|dobro jutro|dobra večer|oprostite|hvala(?: lijepa| vam)?|prodavač) )*(?:(dobro |onda |super |hvala( ali)? )*(uzet ću ih|uzimam ih|kupit ću ih|kupujem ih|preskupe su|to je preskupo|razmislit ću|ne hvala)( hvala)?)(?: (?:hvala(?: lijepa| vam)?|a ti|a vi|molim(?: vas)?|prodavač))*$",
            "suggestion": "Uzet ću ih.",
            "suggestionAudioSrc": "/audio/hr/a2/module-05/uzet-cu-ih.mp3"
          },
          {
            "kind": "line",
            "line": {
              "speaker": "Prodavač",
              "text": "U redu, hvala vam.",
              "translation": "W porządku, dziękuję.",
              "audioSrc": "/audio/hr/a2/module-05/u-redu-hvala-vam-m.mp3"
            }
          }
        ]
      },
      {
        "id": "free",
        "stage": "dialog",
        "type": "free",
        "instruction": "Porównaj dwie rzeczy w sklepie (2 zdania).",
        "points": [
          "co jest tańsze / droższe",
          "co jest większe / mniejsze"
        ],
        "keywords": [
          {
            "any": [
              "veći",
              "veća",
              "veće",
              "manji",
              "manja",
              "manje",
              "jeftiniji",
              "jeftinija",
              "jeftinije",
              "skuplji",
              "skuplja",
              "skuplje",
              "duži",
              "duža",
              "duže",
              "kraći",
              "kraća",
              "kraće"
            ],
            "label": "stopień wyższy"
          },
          {
            "any": [
              "od",
              "nego"
            ],
            "label": "od / nego"
          }
        ],
        "minSentences": 2,
        "sample": "Ova jakna je jeftinija od one. Ali onaj kaput je topliji.",
        "sampleAudioSrc": "/audio/hr/a2/module-05/ova-jakna-je-jeftinija-od-one-ali-onaj-kaput-je-topliji.mp3"
      },
      {
        "id": "summary",
        "stage": "summary",
        "type": "summary",
        "title": "Lekcja ukończona",
        "recap": [
          {
            "target": "Imate li veći broj?",
            "source": "Ma Pani większy rozmiar?",
            "audioSrc": "/audio/hr/a2/module-05/imate-li-veci-broj.mp3"
          },
          {
            "target": "Ova jakna je jeftinija od one.",
            "source": "Ta kurtka jest tańsza od tamtej.",
            "audioSrc": "/audio/hr/a2/module-05/ova-jakna-je-jeftinija-od-one.mp3"
          },
          {
            "target": "Crne cipele su skuplje nego bijele.",
            "source": "Czarne buty są droższe niż białe.",
            "audioSrc": "/audio/hr/a2/module-05/crne-cipele-su-skuplje-nego-bijele.mp3"
          },
          {
            "target": "Trebam manju veličinu.",
            "source": "Potrzebuję mniejszego rozmiaru.",
            "audioSrc": "/audio/hr/a2/module-05/trebam-manju-velicinu.mp3"
          }
        ]
      }
    ]
  },
  material: {
    "sourceLessonId": "a2-23",
    "grammarFocus": "stopień wyższy przymiotników: veći, manji, jeftiniji, skuplji, duži, kraći; od + dopełniacz i nego; ovaj / taj / onaj",
    "communicativeGoal": "Porównać rzeczy w sklepie i poprosić o inny rozmiar.",
    "sources": [
      "https://www.coe.int/en/web/common-European-framework-reference-languages/table-1-cefr-3.3-common-reference-levels-global-scale",
      "https://www.coe.int/en/web/common-european-framework-reference-languages/cefr-descriptors-search",
      "https://croaticum.ffzg.unizg.hr/?page_id=1106"
    ],
    "records": [
      {
        "recordId": "A2-0555",
        "type": "lesson",
        "sequence": 0,
        "hr": "",
        "pl": "",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "",
        "acceptedAnswers": [],
        "notes": "Projekt autorski oparty na deskryptorach CEFR A2 oraz zakresie kursów Croaticum na poziomie A2. Treści nie są kopią podręcznika. Wymaga przeglądu native speakera.",
        "tags": [
          "curriculum",
          "cefr-a2",
          "croatian"
        ]
      },
      {
        "recordId": "A2-0556",
        "type": "vocabulary",
        "sequence": 1,
        "hr": "veći",
        "pl": "większy",
        "lemma": "velik",
        "partOfSpeech": "adjective",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "veći"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A2-0557",
        "type": "vocabulary",
        "sequence": 2,
        "hr": "manji",
        "pl": "mniejszy",
        "lemma": "malen",
        "partOfSpeech": "adjective",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "manji"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A2-0558",
        "type": "vocabulary",
        "sequence": 3,
        "hr": "jeftiniji",
        "pl": "tańszy",
        "lemma": "jeftin",
        "partOfSpeech": "adjective",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "jeftiniji"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A2-0559",
        "type": "vocabulary",
        "sequence": 4,
        "hr": "skuplji",
        "pl": "droższy",
        "lemma": "skup",
        "partOfSpeech": "adjective",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "skuplji"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A2-0560",
        "type": "vocabulary",
        "sequence": 5,
        "hr": "kraći",
        "pl": "krótszy",
        "lemma": "kratak",
        "partOfSpeech": "adjective",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "kraći"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A2-0561",
        "type": "vocabulary",
        "sequence": 6,
        "hr": "duži",
        "pl": "dłuższy",
        "lemma": "dug",
        "partOfSpeech": "adjective",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "duži"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A2-0562",
        "type": "vocabulary",
        "sequence": 7,
        "hr": "onaj",
        "pl": "tamten",
        "lemma": "onaj",
        "partOfSpeech": "pronoun",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "onaj"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A2-0563",
        "type": "vocabulary",
        "sequence": 8,
        "hr": "popust",
        "pl": "zniżka / rabat",
        "lemma": "popust",
        "partOfSpeech": "noun",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "popust"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A2-0564",
        "type": "vocabulary",
        "sequence": 9,
        "hr": "rasprodaja",
        "pl": "wyprzedaż",
        "lemma": "rasprodaja",
        "partOfSpeech": "noun",
        "exerciseType": "flashcard|recognition",
        "acceptedAnswers": [
          "rasprodaja"
        ],
        "notes": "Słownictwo uzupełniające: lista „Więcej przydatnych słów” z nagraniami, rozpoznanie i fiszki.",
        "tags": [
          "vocab",
          "supplement"
        ]
      },
      {
        "recordId": "A2-0565",
        "type": "vocabulary",
        "sequence": 10,
        "hr": "najjeftiniji",
        "pl": "najtańszy",
        "lemma": "jeftin",
        "partOfSpeech": "adjective",
        "exerciseType": "flashcard|recognition",
        "acceptedAnswers": [
          "najjeftiniji"
        ],
        "notes": "Słownictwo uzupełniające: lista „Więcej przydatnych słów” z nagraniami, rozpoznanie i fiszki.",
        "tags": [
          "vocab",
          "supplement"
        ]
      },
      {
        "recordId": "A2-0566",
        "type": "vocabulary",
        "sequence": 11,
        "hr": "isti",
        "pl": "taki sam",
        "lemma": "isti",
        "partOfSpeech": "adjective",
        "exerciseType": "flashcard|recognition",
        "acceptedAnswers": [
          "isti"
        ],
        "notes": "Słownictwo uzupełniające: lista „Więcej przydatnych słów” z nagraniami, rozpoznanie i fiszki.",
        "tags": [
          "vocab",
          "supplement"
        ]
      },
      {
        "recordId": "A2-0567",
        "type": "sentence",
        "sequence": 1,
        "hr": "Imate li veći broj?",
        "pl": "Ma Pani większy rozmiar?",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "Imate li veći broj?"
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych akceptuj warianty z accepted_answers.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A2-0568",
        "type": "sentence",
        "sequence": 2,
        "hr": "Ova jakna je jeftinija od one.",
        "pl": "Ta kurtka jest tańsza od tamtej.",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "Ova jakna je jeftinija od one.",
          "Ova jakna je jeftinija nego ona."
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych akceptuj warianty z accepted_answers.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A2-0569",
        "type": "sentence",
        "sequence": 3,
        "hr": "Crne cipele su skuplje nego bijele.",
        "pl": "Czarne buty są droższe niż białe.",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "Crne cipele su skuplje nego bijele.",
          "Crne cipele su skuplje od bijelih."
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych akceptuj warianty z accepted_answers.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A2-0570",
        "type": "sentence",
        "sequence": 4,
        "hr": "Trebam manju veličinu.",
        "pl": "Potrzebuję mniejszego rozmiaru.",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "Trebam manju veličinu."
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych akceptuj warianty z accepted_answers.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A2-0571",
        "type": "sentence",
        "sequence": 5,
        "hr": "Ove hlače su duže.",
        "pl": "Te spodnie są dłuższe.",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "Ove hlače su duže."
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych akceptuj warianty z accepted_answers.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A2-0572",
        "type": "sentence",
        "sequence": 6,
        "hr": "Ta haljina je kraća.",
        "pl": "Ta sukienka jest krótsza.",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "Ta haljina je kraća."
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych akceptuj warianty z accepted_answers.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A2-0573",
        "type": "sentence",
        "sequence": 7,
        "hr": "Sviđa mi se onaj kaput.",
        "pl": "Podoba mi się tamten płaszcz.",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "Sviđa mi se onaj kaput."
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych akceptuj warianty z accepted_answers.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A2-0574",
        "type": "sentence",
        "sequence": 8,
        "hr": "Ima li popusta?",
        "pl": "Czy jest jakaś zniżka?",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "Ima li popusta?"
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych akceptuj warianty z accepted_answers.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A2-0575",
        "type": "sentence",
        "sequence": 9,
        "hr": "Danas je velika rasprodaja.",
        "pl": "Dziś jest duża wyprzedaż.",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "listening|comprehension",
        "acceptedAnswers": [
          "Danas je velika rasprodaja."
        ],
        "notes": "Zdanie przykładowe: odsłuch w kroku „Nowe słowa w zdaniach”, bez oceniania.",
        "tags": [
          "sentence",
          "example"
        ]
      },
      {
        "recordId": "A2-0576",
        "type": "sentence",
        "sequence": 10,
        "hr": "Ovo je najjeftinija jakna.",
        "pl": "To jest najtańsza kurtka.",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "listening|comprehension",
        "acceptedAnswers": [
          "Ovo je najjeftinija jakna."
        ],
        "notes": "Zdanie przykładowe: odsłuch w kroku „Nowe słowa w zdaniach”, bez oceniania.",
        "tags": [
          "sentence",
          "example"
        ]
      },
      {
        "recordId": "A2-0577",
        "type": "sentence",
        "sequence": 11,
        "hr": "Imate li istu majicu u crnoj boji?",
        "pl": "Ma Pani taką samą koszulkę w czarnym kolorze?",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "listening|comprehension",
        "acceptedAnswers": [
          "Imate li istu majicu u crnoj boji?"
        ],
        "notes": "Zdanie przykładowe: odsłuch w kroku „Nowe słowa w zdaniach”, bez oceniania.",
        "tags": [
          "sentence",
          "example"
        ]
      },
      {
        "recordId": "A2-0578",
        "type": "exercise_blueprint",
        "sequence": 1,
        "hr": "",
        "pl": "",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "multiple_choice",
        "acceptedAnswers": [],
        "notes": "Wybierz poprawne znaczenie lub formę w krótkim zdaniu w perfekcie.",
        "tags": [
          "exercise",
          "lesson-player"
        ]
      },
      {
        "recordId": "A2-0579",
        "type": "exercise_blueprint",
        "sequence": 2,
        "hr": "",
        "pl": "",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation",
        "acceptedAnswers": [],
        "notes": "Przetłumacz krótkie zdanie PL→HR, akceptując poprawne warianty szyku i rodzaju.",
        "tags": [
          "exercise",
          "lesson-player"
        ]
      },
      {
        "recordId": "A2-0580",
        "type": "exercise_blueprint",
        "sequence": 3,
        "hr": "",
        "pl": "",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "free_response",
        "acceptedAnswers": [],
        "notes": "Napisz 2–3 własne zdania z materiałem lekcji; oceń łagodnie słowa kluczowe.",
        "tags": [
          "exercise",
          "lesson-player"
        ]
      }
    ]
  },
};
