// AUTO-GENERATED by scripts/generate-curriculum.mjs — nie edytuj ręcznie.
// a2-05-04 · Reklamacja i zwrot
// Źródło: curriculum/hr-a2/lexodromia_hr_A2_curriculum.csv (sha256 c31e8911b38176e3…) + didactics.json
import type { GeneratedLesson } from "../../../types";

export const LESSON: GeneratedLesson = {
  content: {
    "lessonId": "a2-05-04",
    "vocabulary": [
      {
        "target": "vratiti",
        "source": "zwrócić / oddać",
        "lemma": "vratiti",
        "partOfSpeech": "verb",
        "recordId": "A2-0582",
        "audioSrc": "/audio/hr/a2/module-05/vratiti.mp3"
      },
      {
        "target": "zamijeniti",
        "source": "wymienić",
        "lemma": "zamijeniti",
        "partOfSpeech": "verb",
        "recordId": "A2-0583",
        "audioSrc": "/audio/hr/a2/module-05/zamijeniti.mp3"
      },
      {
        "target": "pokvaren",
        "source": "zepsuty",
        "lemma": "pokvaren",
        "partOfSpeech": "adjective",
        "recordId": "A2-0584",
        "audioSrc": "/audio/hr/a2/module-05/pokvaren.mp3"
      },
      {
        "target": "oštećen",
        "source": "uszkodzony",
        "lemma": "oštećen",
        "partOfSpeech": "adjective",
        "recordId": "A2-0585",
        "audioSrc": "/audio/hr/a2/module-05/ostecen.mp3"
      },
      {
        "target": "jamstvo",
        "source": "gwarancja",
        "lemma": "jamstvo",
        "partOfSpeech": "noun",
        "recordId": "A2-0586",
        "audioSrc": "/audio/hr/a2/module-05/jamstvo.mp3"
      },
      {
        "target": "reklamacija",
        "source": "reklamacja",
        "lemma": "reklamacija",
        "partOfSpeech": "noun",
        "recordId": "A2-0587",
        "audioSrc": "/audio/hr/a2/module-05/reklamacija.mp3"
      },
      {
        "target": "povrat novca",
        "source": "zwrot pieniędzy",
        "lemma": "povrat",
        "partOfSpeech": "phrase",
        "recordId": "A2-0588",
        "audioSrc": "/audio/hr/a2/module-05/povrat-novca.mp3"
      },
      {
        "target": "potvrda",
        "source": "potwierdzenie",
        "lemma": "potvrda",
        "partOfSpeech": "noun",
        "recordId": "A2-0589",
        "audioSrc": "/audio/hr/a2/module-05/potvrda.mp3"
      },
      {
        "target": "uređaj",
        "source": "urządzenie",
        "lemma": "uređaj",
        "partOfSpeech": "noun",
        "recordId": "A2-0590",
        "audioSrc": "/audio/hr/a2/module-05/uredjaj.mp3"
      },
      {
        "target": "kutija",
        "source": "pudełko",
        "lemma": "kutija",
        "partOfSpeech": "noun",
        "recordId": "A2-0591",
        "audioSrc": "/audio/hr/a2/module-05/kutija.mp3"
      },
      {
        "target": "ekran",
        "source": "ekran",
        "lemma": "ekran",
        "partOfSpeech": "noun",
        "recordId": "A2-0592",
        "audioSrc": "/audio/hr/a2/module-05/ekran.mp3"
      },
      {
        "target": "Ne radi.",
        "source": "Nie działa.",
        "lemma": "raditi",
        "partOfSpeech": "phrase",
        "recordId": "A2-0593",
        "audioSrc": "/audio/hr/a2/module-05/ne-radi.mp3"
      }
    ],
    "steps": [
      {
        "id": "intro",
        "stage": "intro",
        "type": "intro",
        "title": "Reklamacja i zwrot",
        "body": "Po tej lekcji będziesz umieć złożyć reklamację i poprosić o wymianę albo zwrot pieniędzy.",
        "goalsTitle": "Powiesz między innymi",
        "goals": [
          {
            "target": "Htio bih vratiti ove cipele.",
            "source": "Chciałbym zwrócić te buty.",
            "audioSrc": "/audio/hr/a2/module-05/htio-bih-vratiti-ove-cipele.mp3"
          },
          {
            "target": "Kupila sam ovaj telefon jučer, ali ne radi.",
            "source": "Kupiłam wczoraj ten telefon, ale nie działa.",
            "audioSrc": "/audio/hr/a2/module-05/kupila-sam-ovaj-telefon-jucer-ali-ne-radi.mp3"
          },
          {
            "target": "Možete li ga zamijeniti?",
            "source": "Czy może go Pan wymienić?",
            "audioSrc": "/audio/hr/a2/module-05/mozete-li-ga-zamijeniti.mp3"
          }
        ]
      },
      {
        "id": "word-1",
        "stage": "words",
        "type": "word",
        "target": "vratiti",
        "source": "zwrócić / oddać",
        "partOfSpeech": "czasownik",
        "example": {
          "target": "Htio bih vratiti ove cipele.",
          "source": "Chciałbym zwrócić te buty.",
          "audioSrc": "/audio/hr/a2/module-05/htio-bih-vratiti-ove-cipele.mp3"
        },
        "conjugation": {
          "present": [
            "vratim",
            "vratiš",
            "vrati",
            "vratimo",
            "vratite",
            "vrate"
          ],
          "past": [
            "vratio",
            "vratila",
            "vratili"
          ],
          "future": "vratit ću",
          "audioSrc": "/audio/hr/a2/module-05/vratim-vratis-vrati-vratimo-vratite-vrate-vratio-vratila-vra.mp3"
        },
        "audioSrc": "/audio/hr/a2/module-05/vratiti.mp3"
      },
      {
        "id": "word-2",
        "stage": "words",
        "type": "word",
        "target": "zamijeniti",
        "source": "wymienić",
        "partOfSpeech": "czasownik",
        "example": {
          "target": "Možete li ga zamijeniti?",
          "source": "Czy może go Pan wymienić?",
          "audioSrc": "/audio/hr/a2/module-05/mozete-li-ga-zamijeniti.mp3"
        },
        "conjugation": {
          "present": [
            "zamijenim",
            "zamijeniš",
            "zamijeni",
            "zamijenimo",
            "zamijenite",
            "zamijene"
          ],
          "past": [
            "zamijenio",
            "zamijenila",
            "zamijenili"
          ],
          "future": "zamijenit ću",
          "audioSrc": "/audio/hr/a2/module-05/zamijenim-zamijenis-zamijeni-zamijenimo-zamijenite-zamijene.mp3"
        },
        "audioSrc": "/audio/hr/a2/module-05/zamijeniti.mp3"
      },
      {
        "id": "word-3",
        "stage": "words",
        "type": "word",
        "target": "pokvaren",
        "source": "zepsuty",
        "partOfSpeech": "przymiotnik",
        "example": {
          "target": "Punjač je pokvaren.",
          "source": "Ładowarka jest zepsuta.",
          "audioSrc": "/audio/hr/a2/module-05/punjac-je-pokvaren.mp3"
        },
        "audioSrc": "/audio/hr/a2/module-05/pokvaren.mp3"
      },
      {
        "id": "check-1",
        "stage": "words",
        "type": "choice",
        "instruction": "Co znaczy to słowo?",
        "prompt": "vratiti",
        "options": [
          "zwrócić / oddać",
          "reklamacja",
          "uszkodzony"
        ],
        "correctIndex": 0,
        "targetText": "prompt",
        "promptAudioSrc": "/audio/hr/a2/module-05/vratiti.mp3"
      },
      {
        "id": "word-4",
        "stage": "words",
        "type": "word",
        "target": "oštećen",
        "source": "uszkodzony",
        "partOfSpeech": "przymiotnik",
        "example": {
          "target": "Kutija je oštećena.",
          "source": "Pudełko jest uszkodzone.",
          "audioSrc": "/audio/hr/a2/module-05/kutija-je-ostecena.mp3"
        },
        "audioSrc": "/audio/hr/a2/module-05/ostecen.mp3"
      },
      {
        "id": "word-5",
        "stage": "words",
        "type": "word",
        "target": "jamstvo",
        "source": "gwarancja",
        "partOfSpeech": "rzeczownik",
        "example": {
          "target": "Telefon ima dvije godine jamstva.",
          "source": "Telefon ma dwa lata gwarancji.",
          "audioSrc": "/audio/hr/a2/module-05/telefon-ima-dvije-godine-jamstva.mp3"
        },
        "audioSrc": "/audio/hr/a2/module-05/jamstvo.mp3"
      },
      {
        "id": "word-6",
        "stage": "words",
        "type": "word",
        "target": "reklamacija",
        "source": "reklamacja",
        "partOfSpeech": "rzeczownik",
        "example": {
          "target": "Ispunite obrazac za reklamaciju.",
          "source": "Proszę wypełnić formularz reklamacyjny.",
          "audioSrc": "/audio/hr/a2/module-05/ispunite-obrazac-za-reklamaciju.mp3"
        },
        "audioSrc": "/audio/hr/a2/module-05/reklamacija.mp3"
      },
      {
        "id": "check-2",
        "stage": "words",
        "type": "choice",
        "instruction": "Jak powiesz to po chorwacku?",
        "prompt": "gwarancja",
        "options": [
          "povrat novca",
          "jamstvo",
          "oštećen"
        ],
        "correctIndex": 1,
        "targetText": "options",
        "answerAudioSrc": "/audio/hr/a2/module-05/jamstvo.mp3"
      },
      {
        "id": "word-7",
        "stage": "words",
        "type": "word",
        "target": "povrat novca",
        "source": "zwrot pieniędzy",
        "partOfSpeech": "zwrot",
        "example": {
          "target": "Želim povrat novca.",
          "source": "Chcę zwrotu pieniędzy.",
          "audioSrc": "/audio/hr/a2/module-05/zelim-povrat-novca.mp3"
        },
        "audioSrc": "/audio/hr/a2/module-05/povrat-novca.mp3"
      },
      {
        "id": "word-8",
        "stage": "words",
        "type": "word",
        "target": "potvrda",
        "source": "potwierdzenie",
        "partOfSpeech": "rzeczownik",
        "example": {
          "target": "Dobit ćete potvrdu e-mailom.",
          "source": "Dostanie Pan potwierdzenie e-mailem.",
          "audioSrc": "/audio/hr/a2/module-05/dobit-cete-potvrdu-e-mailom.mp3"
        },
        "audioSrc": "/audio/hr/a2/module-05/potvrda.mp3"
      },
      {
        "id": "check-3",
        "stage": "words",
        "type": "choice",
        "instruction": "Co znaczy to słowo?",
        "prompt": "povrat novca",
        "options": [
          "uszkodzony",
          "reklamacja",
          "zwrot pieniędzy"
        ],
        "correctIndex": 2,
        "targetText": "prompt",
        "promptAudioSrc": "/audio/hr/a2/module-05/povrat-novca.mp3"
      },
      {
        "id": "more-words",
        "stage": "words",
        "type": "vocabList",
        "title": "Więcej przydatnych słów",
        "note": "Odsłuchaj i powtórz na głos. Te słowa trafią do fiszek razem z resztą lekcji.",
        "items": [
          {
            "target": "uređaj",
            "source": "urządzenie",
            "partOfSpeech": "rzeczownik",
            "audioSrc": "/audio/hr/a2/module-05/uredjaj.mp3"
          },
          {
            "target": "kutija",
            "source": "pudełko",
            "partOfSpeech": "rzeczownik",
            "audioSrc": "/audio/hr/a2/module-05/kutija.mp3"
          },
          {
            "target": "ekran",
            "source": "ekran",
            "partOfSpeech": "rzeczownik",
            "audioSrc": "/audio/hr/a2/module-05/ekran.mp3"
          },
          {
            "target": "Ne radi.",
            "source": "Nie działa.",
            "partOfSpeech": "zwrot",
            "audioSrc": "/audio/hr/a2/module-05/ne-radi.mp3"
          }
        ]
      },
      {
        "id": "check-more",
        "stage": "words",
        "type": "choice",
        "instruction": "Co znaczy to słowo?",
        "prompt": "uređaj",
        "options": [
          "urządzenie",
          "Nie działa.",
          "pudełko"
        ],
        "correctIndex": 0,
        "targetText": "prompt",
        "promptAudioSrc": "/audio/hr/a2/module-05/uredjaj.mp3"
      },
      {
        "id": "examples",
        "stage": "words",
        "type": "structure",
        "title": "Nowe słowa w zdaniach",
        "explanation": "Posłuchaj, jak nowe słowa brzmią w krótkich, codziennych zdaniach.",
        "examples": [
          {
            "target": "Uređaj se ne uključuje.",
            "source": "Urządzenie się nie włącza.",
            "audioSrc": "/audio/hr/a2/module-05/uredjaj-se-ne-ukljucuje.mp3"
          },
          {
            "target": "Sačuvajte kutiju i račun.",
            "source": "Proszę zachować pudełko i paragon.",
            "audioSrc": "/audio/hr/a2/module-05/sacuvajte-kutiju-i-racun.mp3"
          },
          {
            "target": "Ekran ne radi.",
            "source": "Ekran nie działa.",
            "audioSrc": "/audio/hr/a2/module-05/ekran-ne-radi.mp3"
          }
        ]
      },
      {
        "id": "structure",
        "stage": "structure",
        "type": "structure",
        "title": "Htio bih vratiti…",
        "explanation": "Grzeczna prośba w sklepie: Htio bih / Htjela bih + bezokolicznik (chciałbym / chciałabym): Htio bih vratiti ove cipele. Problem opisujesz w perfekcie i w czasie teraźniejszym: Kupila sam ga jučer, ali ne radi. Pokvaren (zepsuty) i oštećen (uszkodzony) zgadzają się z rzeczą: pokvaren punjač, pokvarena perilica, oštećena kutija.",
        "table": [
          {
            "label": "Prośba",
            "rows": [
              {
                "base": "zwrot",
                "form": "Htio bih vratiti ovo.",
                "meaning": "Chciałbym to zwrócić.",
                "audioSrc": "/audio/hr/a2/module-05/htio-bih-vratiti-ovo.mp3"
              },
              {
                "base": "wymiana",
                "form": "Možete li ga zamijeniti?",
                "meaning": "Może go Pan wymienić?",
                "audioSrc": "/audio/hr/a2/module-05/mozete-li-ga-zamijeniti.mp3"
              },
              {
                "base": "pieniądze",
                "form": "Želim povrat novca.",
                "meaning": "Chcę zwrotu pieniędzy.",
                "audioSrc": "/audio/hr/a2/module-05/zelim-povrat-novca.mp3"
              },
              {
                "base": "problem",
                "form": "Kupila sam ga jučer, ali ne radi.",
                "meaning": "Kupiłam go wczoraj, ale nie działa.",
                "audioSrc": "/audio/hr/a2/module-05/kupila-sam-ga-jucer-ali-ne-radi.mp3"
              }
            ]
          },
          {
            "label": "pokvaren · oštećen",
            "rows": [
              {
                "base": "on (punjač)",
                "form": "Punjač je pokvaren.",
                "meaning": "Ładowarka jest zepsuta.",
                "audioSrc": "/audio/hr/a2/module-05/punjac-je-pokvaren.mp3"
              },
              {
                "base": "ona (kutija)",
                "form": "Kutija je oštećena.",
                "meaning": "Pudełko jest uszkodzone.",
                "audioSrc": "/audio/hr/a2/module-05/kutija-je-ostecena.mp3"
              },
              {
                "base": "ono (pakiranje)",
                "form": "Pakiranje je oštećeno.",
                "meaning": "Opakowanie jest uszkodzone.",
                "audioSrc": "/audio/hr/a2/module-05/pakiranje-je-osteceno.mp3"
              }
            ]
          }
        ],
        "examples": [
          {
            "target": "Htio bih vratiti ove cipele.",
            "source": "Chciałbym zwrócić te buty.",
            "audioSrc": "/audio/hr/a2/module-05/htio-bih-vratiti-ove-cipele.mp3"
          },
          {
            "target": "Kupila sam ovaj telefon jučer, ali ne radi.",
            "source": "Kupiłam wczoraj ten telefon, ale nie działa.",
            "audioSrc": "/audio/hr/a2/module-05/kupila-sam-ovaj-telefon-jucer-ali-ne-radi.mp3"
          },
          {
            "target": "Možete li ga zamijeniti?",
            "source": "Czy może go Pan wymienić?",
            "audioSrc": "/audio/hr/a2/module-05/mozete-li-ga-zamijeniti.mp3"
          },
          {
            "target": "Želim povrat novca.",
            "source": "Chcę zwrotu pieniędzy.",
            "audioSrc": "/audio/hr/a2/module-05/zelim-povrat-novca.mp3"
          }
        ],
        "note": "Gwarancja: Telefon ima dvije godine jamstva — telefon ma dwa lata gwarancji."
      },
      {
        "id": "gap",
        "stage": "structure",
        "type": "gap",
        "instruction": "Uzupełnij lukę.",
        "before": "Htio bih",
        "after": "ove cipele.",
        "accepted": [
          "vratiti"
        ],
        "translation": "Chciałbym zwrócić te buty.",
        "answerAudioSrc": "/audio/hr/a2/module-05/htio-bih-vratiti-ove-cipele.mp3"
      },
      {
        "id": "translate-1",
        "stage": "practice",
        "type": "translate",
        "instruction": "Przetłumacz na chorwacki.",
        "prompt": "Czy może go Pan wymienić?",
        "accepted": [
          "Možete li ga zamijeniti?"
        ],
        "answerAudioSrc": "/audio/hr/a2/module-05/mozete-li-ga-zamijeniti.mp3"
      },
      {
        "id": "order",
        "stage": "practice",
        "type": "order",
        "instruction": "Ułóż zdanie.",
        "translation": "Proszę wypełnić formularz reklamacyjny.",
        "tokens": [
          "obrazac",
          "reklamaciju",
          "za",
          "ispunite"
        ],
        "accepted": [
          "Ispunite obrazac za reklamaciju."
        ],
        "answerAudioSrc": "/audio/hr/a2/module-05/ispunite-obrazac-za-reklamaciju.mp3"
      },
      {
        "id": "choice-1",
        "stage": "practice",
        "type": "choice",
        "instruction": "Wybierz poprawne zdanie.",
        "prompt": "Chciałabym zwrócić tę kurtkę.",
        "options": [
          "Htio bih vratiti ova jakna.",
          "Htjela sam vratiti ovu jaknu.",
          "Htjela bih vratiti ovu jaknu."
        ],
        "correctIndex": 2,
        "explanation": "Kobieta: htjela bih + bezokolicznik; jaknu w bierniku.",
        "targetText": "options",
        "answerAudioSrc": "/audio/hr/a2/module-05/htjela-bih-vratiti-ovu-jaknu.mp3"
      },
      {
        "id": "comprehend",
        "stage": "practice",
        "type": "choice",
        "instruction": "Co znaczy to zdanie?",
        "prompt": "Telefon ima dvije godine jamstva.",
        "options": [
          "Telefon ma dwa lata gwarancji.",
          "Chciałbym zwrócić te buty.",
          "Kupiłam wczoraj ten telefon, ale nie działa."
        ],
        "correctIndex": 0,
        "targetText": "prompt",
        "promptAudioSrc": "/audio/hr/a2/module-05/telefon-ima-dvije-godine-jamstva.mp3"
      },
      {
        "id": "translate-2",
        "stage": "practice",
        "type": "translate",
        "instruction": "Przetłumacz na chorwacki.",
        "prompt": "Chcę zwrotu pieniędzy.",
        "accepted": [
          "Želim povrat novca.",
          "Ja želim povrat novca."
        ],
        "answerAudioSrc": "/audio/hr/a2/module-05/zelim-povrat-novca.mp3"
      },
      {
        "id": "translate-more",
        "stage": "practice",
        "type": "translate",
        "instruction": "Przetłumacz na chorwacki.",
        "prompt": "Ekran nie działa.",
        "accepted": [
          "Ekran ne radi."
        ],
        "answerAudioSrc": "/audio/hr/a2/module-05/ekran-ne-radi.mp3"
      },
      {
        "id": "listening",
        "stage": "dialog",
        "type": "listening",
        "instruction": "Posłuchaj dialogu i odpowiedz na pytanie.",
        "title": "Zwrot w sklepie",
        "lines": [
          {
            "speaker": "Ana",
            "text": "Dobar dan. Prošli tjedan sam kupila ove slušalice, ali lijeva ne radi.",
            "translation": "Dzień dobry. W zeszłym tygodniu kupiłam te słuchawki, ale lewa nie działa.",
            "audio": "/audio/listening/hr-a2/a2-povrat-robe/01-ana.mp3"
          },
          {
            "speaker": "Marko",
            "text": "Žao mi je. Imate li račun?",
            "translation": "Przykro mi. Ma Pani paragon?",
            "audio": "/audio/listening/hr-a2/a2-povrat-robe/02-marko.mp3"
          },
          {
            "speaker": "Ana",
            "text": "Imam, evo ga. Htjela bih ih zamijeniti.",
            "translation": "Mam, proszę. Chciałabym je wymienić.",
            "audio": "/audio/listening/hr-a2/a2-povrat-robe/03-ana.mp3"
          },
          {
            "speaker": "Marko",
            "text": "Nažalost, taj model više nemamo. Mogu vam vratiti novac.",
            "translation": "Niestety nie mamy już tego modelu. Mogę zwrócić Pani pieniądze.",
            "audio": "/audio/listening/hr-a2/a2-povrat-robe/04-marko.mp3"
          },
          {
            "speaker": "Ana",
            "text": "U redu, onda povrat novca, molim.",
            "translation": "W porządku, to poproszę o zwrot pieniędzy.",
            "audio": "/audio/listening/hr-a2/a2-povrat-robe/05-ana.mp3"
          },
          {
            "speaker": "Marko",
            "text": "Novac će biti na vašoj kartici za tri do pet dana.",
            "translation": "Pieniądze będą na Pani karcie w ciągu trzech do pięciu dni.",
            "audio": "/audio/listening/hr-a2/a2-povrat-robe/06-marko.mp3"
          }
        ],
        "questions": [
          {
            "prompt": "Co dostanie Ana?",
            "options": [
              "Zwrot pieniędzy na kartę",
              "Nowe słuchawki tego samego modelu",
              "Bon do sklepu"
            ],
            "correctIndex": 0
          }
        ]
      },
      {
        "id": "model",
        "stage": "dialog",
        "type": "listen",
        "title": "Zepsuty telefon",
        "lines": [
          {
            "speaker": "Ana",
            "text": "Dobar dan. Kupila sam ovaj telefon prošli tjedan, ali ne radi.",
            "translation": "Dzień dobry. Kupiłam ten telefon w zeszłym tygodniu, ale nie działa.",
            "audioSrc": "/audio/hr/a2/module-05/dobar-dan-kupila-sam-ovaj-telefon-prosli-tjedan-ali-ne-radi.mp3"
          },
          {
            "speaker": "Prodavač",
            "text": "Žao mi je. Imate li račun?",
            "translation": "Przykro mi. Ma Pani paragon?",
            "audioSrc": "/audio/hr/a2/module-05/zao-mi-je-imate-li-racun-m.mp3"
          },
          {
            "speaker": "Ana",
            "text": "Imam, izvolite. Ekran se ne uključuje.",
            "translation": "Mam, proszę. Ekran się nie włącza.",
            "audioSrc": "/audio/hr/a2/module-05/imam-izvolite-ekran-se-ne-ukljucuje.mp3"
          },
          {
            "speaker": "Prodavač",
            "text": "Telefon ima dvije godine jamstva. Možemo ga zamijeniti ili vam vratiti novac.",
            "translation": "Telefon ma dwa lata gwarancji. Możemy go wymienić albo zwrócić Pani pieniądze.",
            "audioSrc": "/audio/hr/a2/module-05/telefon-ima-dvije-godine-jamstva-mozemo-ga-zamijeniti-ili-va-m.mp3"
          },
          {
            "speaker": "Ana",
            "text": "Radije bih novi telefon.",
            "translation": "Wolałabym nowy telefon.",
            "audioSrc": "/audio/hr/a2/module-05/radije-bih-novi-telefon.mp3"
          },
          {
            "speaker": "Prodavač",
            "text": "U redu. Ispunite ovaj obrazac, molim.",
            "translation": "W porządku. Proszę wypełnić ten formularz.",
            "audioSrc": "/audio/hr/a2/module-05/u-redu-ispunite-ovaj-obrazac-molim-m.mp3"
          }
        ]
      },
      {
        "id": "dialog",
        "stage": "dialog",
        "type": "dialog",
        "title": "Reklamacja",
        "turns": [
          {
            "kind": "line",
            "line": {
              "speaker": "Prodavač",
              "text": "Dobar dan, izvolite?",
              "translation": "Dzień dobry, w czym mogę pomóc?",
              "audioSrc": "/audio/hr/a2/module-03/dobar-dan-izvolite-m.mp3"
            }
          },
          {
            "kind": "reply",
            "prompt": "Powiedz, co kupiłeś / kupiłaś i co nie działa.",
            "accepted": [
              "Kupila sam ovaj telefon jučer, ali ne radi.",
              "Kupio sam ovaj telefon jučer, ali ne radi.",
              "Kupio sam ovaj punjač, ali ne radi.",
              "Kupila sam ovaj punjač, ali ne radi."
            ],
            "pattern": "^(?:(?:bok|zdravo|hej|dobar dan|dobro jutro|dobra večer|oprostite|hvala(?: lijepa| vam)?|prodavač) )*(?:((?:kupio|kupila)|(?:kupila|kupio)) sam (ovaj|ovu|ovo|ove) \\p{L}+( \\p{L}+)?( ali| i)? ((on |ona |to |oni |one )?ne (radi|rade)|(je|su) ((?:pokvaren|pokvarena)|(?:pokvarena|pokvaren)|pokvareno|pokvareni|pokvarene|(?:oštećen|oštećena)|(?:oštećena|oštećen)|oštećeno|oštećeni|oštećene))|(ovaj|ova|ovo|ove|moj|moja|moje) \\p{L}+ (ne (radi|rade)|(je|su) ((?:pokvaren|pokvarena)|(?:pokvarena|pokvaren)|pokvareno|pokvareni|pokvarene|(?:oštećen|oštećena)|(?:oštećena|oštećen)|oštećeno|oštećeni|oštećene)))(?: (?:hvala(?: lijepa| vam)?|a ti|a vi|molim(?: vas)?|prodavač))*$",
            "suggestion": "Kupila sam ovaj telefon jučer, ali ne radi.",
            "suggestionAudioSrc": "/audio/hr/a2/module-05/kupila-sam-ovaj-telefon-jucer-ali-ne-radi.mp3"
          },
          {
            "kind": "line",
            "line": {
              "speaker": "Prodavač",
              "text": "Imate li račun?",
              "translation": "Ma Pan paragon?",
              "audioSrc": "/audio/hr/a2/module-05/imate-li-racun-m.mp3"
            }
          },
          {
            "kind": "reply",
            "prompt": "Odpowiedz, czy masz paragon.",
            "accepted": [
              "Imam, izvolite.",
              "Ja imam, izvolite.",
              "Nažalost, nemam račun.",
              "Ja nažalost, nemam račun."
            ],
            "pattern": "^(?:(?:bok|zdravo|hej|dobar dan|dobro jutro|dobra večer|oprostite|hvala(?: lijepa| vam)?|prodavač) )*(?:(da |ne |nažalost )?(imam|nemam)( ga| račun| računa)?( izvolite| evo ga| ovdje je)?)(?: (?:hvala(?: lijepa| vam)?|a ti|a vi|molim(?: vas)?|prodavač))*$",
            "suggestion": "Imam, izvolite.",
            "suggestionAudioSrc": "/audio/hr/a2/module-05/imam-izvolite.mp3"
          },
          {
            "kind": "line",
            "line": {
              "speaker": "Prodavač",
              "text": "Možemo ga zamijeniti ili vam vratiti novac.",
              "translation": "Możemy go wymienić albo zwrócić Panu pieniądze.",
              "audioSrc": "/audio/hr/a2/module-05/mozemo-ga-zamijeniti-ili-vam-vratiti-novac-m.mp3"
            }
          },
          {
            "kind": "reply",
            "prompt": "Wybierz: wymiana albo zwrot pieniędzy.",
            "accepted": [
              "Htio bih novi.",
              "Htjela bih novi.",
              "Želim povrat novca.",
              "Ja želim povrat novca."
            ],
            "pattern": "^(?:(?:bok|zdravo|hej|dobar dan|dobro jutro|dobra večer|oprostite|hvala(?: lijepa| vam)?|prodavač) )*(?:((?:htio|htjela) bih|(?:htjela|htio) bih|radije bih|želim|molim)( novi| novu| novo| zamjenu| povrat novca| da ga zamijenite| da mi vratite novac)( molim)?|(zamjenu|povrat novca|novi|novu)( molim)?)(?: (?:hvala(?: lijepa| vam)?|a ti|a vi|molim(?: vas)?|prodavač))*$",
            "suggestion": "Htio bih novi.",
            "suggestionAudioSrc": "/audio/hr/a2/module-05/htio-bih-novi.mp3"
          },
          {
            "kind": "line",
            "line": {
              "speaker": "Prodavač",
              "text": "U redu, nema problema.",
              "translation": "W porządku, nie ma problemu.",
              "audioSrc": "/audio/hr/a2/module-05/u-redu-nema-problema-m.mp3"
            }
          }
        ]
      },
      {
        "id": "free",
        "stage": "dialog",
        "type": "free",
        "instruction": "Napisz 2–3 zdania reklamacji: co kupiłeś, co nie działa i czego chcesz.",
        "points": [
          "co kupiłeś / kupiłaś",
          "problem",
          "wymiana albo zwrot"
        ],
        "keywords": [
          {
            "any": [
              "kupio",
              "kupila"
            ],
            "label": "co kupiłeś"
          },
          {
            "any": [
              "radi",
              "pokvaren",
              "pokvarena",
              "pokvareno",
              "oštećen",
              "oštećena",
              "oštećeno"
            ],
            "label": "problem"
          },
          {
            "any": [
              "vratiti",
              "zamijeniti",
              "povrat"
            ],
            "label": "czego chcesz"
          }
        ],
        "minSentences": 2,
        "sample": "Kupio sam ovaj punjač jučer, ali ne radi. Htio bih ga zamijeniti.",
        "sampleAudioSrc": "/audio/hr/a2/module-05/kupio-sam-ovaj-punjac-jucer-ali-ne-radi-htio-bih-ga-zamijeni.mp3"
      },
      {
        "id": "summary",
        "stage": "summary",
        "type": "summary",
        "title": "Lekcja ukończona",
        "recap": [
          {
            "target": "Htio bih vratiti ove cipele.",
            "source": "Chciałbym zwrócić te buty.",
            "audioSrc": "/audio/hr/a2/module-05/htio-bih-vratiti-ove-cipele.mp3"
          },
          {
            "target": "Kupila sam ovaj telefon jučer, ali ne radi.",
            "source": "Kupiłam wczoraj ten telefon, ale nie działa.",
            "audioSrc": "/audio/hr/a2/module-05/kupila-sam-ovaj-telefon-jucer-ali-ne-radi.mp3"
          },
          {
            "target": "Možete li ga zamijeniti?",
            "source": "Czy może go Pan wymienić?",
            "audioSrc": "/audio/hr/a2/module-05/mozete-li-ga-zamijeniti.mp3"
          },
          {
            "target": "Punjač je pokvaren.",
            "source": "Ładowarka jest zepsuta.",
            "audioSrc": "/audio/hr/a2/module-05/punjac-je-pokvaren.mp3"
          }
        ]
      }
    ]
  },
  material: {
    "sourceLessonId": "a2-24",
    "grammarFocus": "Htio / Htjela bih + bezokolicznik (vratiti, zamijeniti); problem w perfekcie (Kupila sam…, ali ne radi); pokvaren / oštećen zgodnie z rodzajem",
    "communicativeGoal": "Złożyć reklamację i poprosić o wymianę albo zwrot pieniędzy.",
    "sources": [
      "https://www.coe.int/en/web/common-European-framework-reference-languages/table-1-cefr-3.3-common-reference-levels-global-scale",
      "https://www.coe.int/en/web/common-european-framework-reference-languages/cefr-descriptors-search",
      "https://croaticum.ffzg.unizg.hr/?page_id=1106"
    ],
    "records": [
      {
        "recordId": "A2-0581",
        "type": "lesson",
        "sequence": 0,
        "hr": "",
        "pl": "",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "",
        "acceptedAnswers": [],
        "notes": "Projekt autorski oparty na deskryptorach CEFR A2 oraz zakresie kursów Croaticum na poziomie A2. Treści nie są kopią podręcznika. Wymaga przeglądu native speakera.",
        "tags": [
          "curriculum",
          "cefr-a2",
          "croatian"
        ]
      },
      {
        "recordId": "A2-0582",
        "type": "vocabulary",
        "sequence": 1,
        "hr": "vratiti",
        "pl": "zwrócić / oddać",
        "lemma": "vratiti",
        "partOfSpeech": "verb",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "vratiti"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A2-0583",
        "type": "vocabulary",
        "sequence": 2,
        "hr": "zamijeniti",
        "pl": "wymienić",
        "lemma": "zamijeniti",
        "partOfSpeech": "verb",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "zamijeniti"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A2-0584",
        "type": "vocabulary",
        "sequence": 3,
        "hr": "pokvaren",
        "pl": "zepsuty",
        "lemma": "pokvaren",
        "partOfSpeech": "adjective",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "pokvaren"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A2-0585",
        "type": "vocabulary",
        "sequence": 4,
        "hr": "oštećen",
        "pl": "uszkodzony",
        "lemma": "oštećen",
        "partOfSpeech": "adjective",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "oštećen"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A2-0586",
        "type": "vocabulary",
        "sequence": 5,
        "hr": "jamstvo",
        "pl": "gwarancja",
        "lemma": "jamstvo",
        "partOfSpeech": "noun",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "jamstvo"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A2-0587",
        "type": "vocabulary",
        "sequence": 6,
        "hr": "reklamacija",
        "pl": "reklamacja",
        "lemma": "reklamacija",
        "partOfSpeech": "noun",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "reklamacija"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A2-0588",
        "type": "vocabulary",
        "sequence": 7,
        "hr": "povrat novca",
        "pl": "zwrot pieniędzy",
        "lemma": "povrat",
        "partOfSpeech": "phrase",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "povrat novca"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A2-0589",
        "type": "vocabulary",
        "sequence": 8,
        "hr": "potvrda",
        "pl": "potwierdzenie",
        "lemma": "potvrda",
        "partOfSpeech": "noun",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "potvrda"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A2-0590",
        "type": "vocabulary",
        "sequence": 9,
        "hr": "uređaj",
        "pl": "urządzenie",
        "lemma": "uređaj",
        "partOfSpeech": "noun",
        "exerciseType": "flashcard|recognition",
        "acceptedAnswers": [
          "uređaj"
        ],
        "notes": "Słownictwo uzupełniające: lista „Więcej przydatnych słów” z nagraniami, rozpoznanie i fiszki.",
        "tags": [
          "vocab",
          "supplement"
        ]
      },
      {
        "recordId": "A2-0591",
        "type": "vocabulary",
        "sequence": 10,
        "hr": "kutija",
        "pl": "pudełko",
        "lemma": "kutija",
        "partOfSpeech": "noun",
        "exerciseType": "flashcard|recognition",
        "acceptedAnswers": [
          "kutija"
        ],
        "notes": "Słownictwo uzupełniające: lista „Więcej przydatnych słów” z nagraniami, rozpoznanie i fiszki.",
        "tags": [
          "vocab",
          "supplement"
        ]
      },
      {
        "recordId": "A2-0592",
        "type": "vocabulary",
        "sequence": 11,
        "hr": "ekran",
        "pl": "ekran",
        "lemma": "ekran",
        "partOfSpeech": "noun",
        "exerciseType": "flashcard|recognition",
        "acceptedAnswers": [
          "ekran"
        ],
        "notes": "Słownictwo uzupełniające: lista „Więcej przydatnych słów” z nagraniami, rozpoznanie i fiszki.",
        "tags": [
          "vocab",
          "supplement"
        ]
      },
      {
        "recordId": "A2-0593",
        "type": "vocabulary",
        "sequence": 12,
        "hr": "Ne radi.",
        "pl": "Nie działa.",
        "lemma": "raditi",
        "partOfSpeech": "phrase",
        "exerciseType": "flashcard|recognition",
        "acceptedAnswers": [
          "Ne radi."
        ],
        "notes": "Słownictwo uzupełniające: lista „Więcej przydatnych słów” z nagraniami, rozpoznanie i fiszki.",
        "tags": [
          "vocab",
          "supplement"
        ]
      },
      {
        "recordId": "A2-0594",
        "type": "sentence",
        "sequence": 1,
        "hr": "Htio bih vratiti ove cipele.",
        "pl": "Chciałbym zwrócić te buty.",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "Htio bih vratiti ove cipele."
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych akceptuj warianty z accepted_answers.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A2-0595",
        "type": "sentence",
        "sequence": 2,
        "hr": "Kupila sam ovaj telefon jučer, ali ne radi.",
        "pl": "Kupiłam wczoraj ten telefon, ale nie działa.",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "Kupila sam ovaj telefon jučer, ali ne radi."
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych akceptuj warianty z accepted_answers.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A2-0596",
        "type": "sentence",
        "sequence": 3,
        "hr": "Možete li ga zamijeniti?",
        "pl": "Czy może go Pan wymienić?",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "Možete li ga zamijeniti?"
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych akceptuj warianty z accepted_answers.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A2-0597",
        "type": "sentence",
        "sequence": 4,
        "hr": "Punjač je pokvaren.",
        "pl": "Ładowarka jest zepsuta.",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "Punjač je pokvaren."
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych akceptuj warianty z accepted_answers.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A2-0598",
        "type": "sentence",
        "sequence": 5,
        "hr": "Kutija je oštećena.",
        "pl": "Pudełko jest uszkodzone.",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "Kutija je oštećena."
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych akceptuj warianty z accepted_answers.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A2-0599",
        "type": "sentence",
        "sequence": 6,
        "hr": "Imate li račun?",
        "pl": "Ma Pani paragon?",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "Imate li račun?"
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych akceptuj warianty z accepted_answers.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A2-0600",
        "type": "sentence",
        "sequence": 7,
        "hr": "Telefon ima dvije godine jamstva.",
        "pl": "Telefon ma dwa lata gwarancji.",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "Telefon ima dvije godine jamstva."
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych akceptuj warianty z accepted_answers.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A2-0601",
        "type": "sentence",
        "sequence": 8,
        "hr": "Želim povrat novca.",
        "pl": "Chcę zwrotu pieniędzy.",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "Želim povrat novca."
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych akceptuj warianty z accepted_answers.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A2-0602",
        "type": "sentence",
        "sequence": 9,
        "hr": "Ispunite obrazac za reklamaciju.",
        "pl": "Proszę wypełnić formularz reklamacyjny.",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "Ispunite obrazac za reklamaciju."
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych akceptuj warianty z accepted_answers.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A2-0603",
        "type": "sentence",
        "sequence": 10,
        "hr": "Dobit ćete potvrdu e-mailom.",
        "pl": "Dostanie Pan potwierdzenie e-mailem.",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "Dobit ćete potvrdu e-mailom."
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych akceptuj warianty z accepted_answers.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A2-0604",
        "type": "sentence",
        "sequence": 11,
        "hr": "Uređaj se ne uključuje.",
        "pl": "Urządzenie się nie włącza.",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "listening|comprehension",
        "acceptedAnswers": [
          "Uređaj se ne uključuje."
        ],
        "notes": "Zdanie przykładowe: odsłuch w kroku „Nowe słowa w zdaniach”, bez oceniania.",
        "tags": [
          "sentence",
          "example"
        ]
      },
      {
        "recordId": "A2-0605",
        "type": "sentence",
        "sequence": 12,
        "hr": "Sačuvajte kutiju i račun.",
        "pl": "Proszę zachować pudełko i paragon.",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "listening|comprehension",
        "acceptedAnswers": [
          "Sačuvajte kutiju i račun."
        ],
        "notes": "Zdanie przykładowe: odsłuch w kroku „Nowe słowa w zdaniach”, bez oceniania.",
        "tags": [
          "sentence",
          "example"
        ]
      },
      {
        "recordId": "A2-0606",
        "type": "sentence",
        "sequence": 13,
        "hr": "Ekran ne radi.",
        "pl": "Ekran nie działa.",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "listening|comprehension",
        "acceptedAnswers": [
          "Ekran ne radi."
        ],
        "notes": "Zdanie przykładowe: odsłuch w kroku „Nowe słowa w zdaniach”, bez oceniania.",
        "tags": [
          "sentence",
          "example"
        ]
      },
      {
        "recordId": "A2-0607",
        "type": "exercise_blueprint",
        "sequence": 1,
        "hr": "",
        "pl": "",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "multiple_choice",
        "acceptedAnswers": [],
        "notes": "Wybierz poprawne znaczenie lub formę w krótkim zdaniu w perfekcie.",
        "tags": [
          "exercise",
          "lesson-player"
        ]
      },
      {
        "recordId": "A2-0608",
        "type": "exercise_blueprint",
        "sequence": 2,
        "hr": "",
        "pl": "",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation",
        "acceptedAnswers": [],
        "notes": "Przetłumacz krótkie zdanie PL→HR, akceptując poprawne warianty szyku i rodzaju.",
        "tags": [
          "exercise",
          "lesson-player"
        ]
      },
      {
        "recordId": "A2-0609",
        "type": "exercise_blueprint",
        "sequence": 3,
        "hr": "",
        "pl": "",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "free_response",
        "acceptedAnswers": [],
        "notes": "Napisz 2–3 własne zdania z materiałem lekcji; oceń łagodnie słowa kluczowe.",
        "tags": [
          "exercise",
          "lesson-player"
        ]
      }
    ]
  },
};
