// AUTO-GENERATED by scripts/generate-a1-curriculum.mjs — nie edytuj ręcznie.
// a1-05-04 · Sklep i zakupy
// Źródło: curriculum/hr-a1/lexodromia_hr_A1_curriculum.csv (sha256 75adf749ae368f10…) + didactics.json
import type { GeneratedLesson } from "../../../types";

export const LESSON: GeneratedLesson = {
  content: {
    "lessonId": "a1-05-04",
    "vocabulary": [
      {
        "target": "koštati",
        "source": "kosztować",
        "lemma": "koštati",
        "partOfSpeech": "verb",
        "recordId": "A1-0416"
      },
      {
        "target": "cijena",
        "source": "cena",
        "lemma": "cijena",
        "partOfSpeech": "noun",
        "recordId": "A1-0417"
      },
      {
        "target": "euro",
        "source": "euro",
        "lemma": "euro",
        "partOfSpeech": "noun",
        "recordId": "A1-0418"
      },
      {
        "target": "kupiti",
        "source": "kupić",
        "lemma": "kupiti",
        "partOfSpeech": "verb",
        "recordId": "A1-0419"
      },
      {
        "target": "tražiti",
        "source": "szukać / prosić o",
        "lemma": "tražiti",
        "partOfSpeech": "verb",
        "recordId": "A1-0420"
      },
      {
        "target": "imati",
        "source": "mieć",
        "lemma": "imati",
        "partOfSpeech": "verb",
        "recordId": "A1-0421"
      },
      {
        "target": "veličina",
        "source": "rozmiar",
        "lemma": "veličina",
        "partOfSpeech": "noun",
        "recordId": "A1-0422"
      },
      {
        "target": "kartica",
        "source": "karta płatnicza",
        "lemma": "kartica",
        "partOfSpeech": "noun",
        "recordId": "A1-0423"
      }
    ],
    "steps": [
      {
        "id": "intro",
        "stage": "intro",
        "type": "intro",
        "title": "Sklep i zakupy",
        "body": "Po tej lekcji będziesz umieć zapytać o cenę i poprosić o produkt.",
        "goalsTitle": "Powiesz między innymi",
        "goals": [
          {
            "target": "Koliko ovo košta?",
            "source": "Ile to kosztuje?"
          },
          {
            "target": "Košta deset eura.",
            "source": "Kosztuje dziesięć euro."
          },
          {
            "target": "Imate li ovo u drugoj veličini?",
            "source": "Czy mają Państwo to w innym rozmiarze?"
          }
        ]
      },
      {
        "id": "word-1",
        "stage": "words",
        "type": "word",
        "target": "koštati",
        "source": "kosztować",
        "partOfSpeech": "czasownik",
        "example": {
          "target": "Koliko ovo košta?",
          "source": "Ile to kosztuje?"
        }
      },
      {
        "id": "word-2",
        "stage": "words",
        "type": "word",
        "target": "cijena",
        "source": "cena",
        "partOfSpeech": "rzeczownik"
      },
      {
        "id": "word-3",
        "stage": "words",
        "type": "word",
        "target": "euro",
        "source": "euro",
        "partOfSpeech": "rzeczownik",
        "example": {
          "target": "Košta deset eura.",
          "source": "Kosztuje dziesięć euro."
        }
      },
      {
        "id": "check-1",
        "stage": "words",
        "type": "choice",
        "instruction": "Co znaczy to słowo?",
        "prompt": "koštati",
        "options": [
          "kosztować",
          "mieć",
          "kupić"
        ],
        "correctIndex": 0,
        "targetText": "prompt"
      },
      {
        "id": "word-4",
        "stage": "words",
        "type": "word",
        "target": "kupiti",
        "source": "kupić",
        "partOfSpeech": "czasownik",
        "example": {
          "target": "Želim kupiti ovu knjigu.",
          "source": "Chcę kupić tę książkę."
        }
      },
      {
        "id": "word-5",
        "stage": "words",
        "type": "word",
        "target": "tražiti",
        "source": "szukać / prosić o",
        "partOfSpeech": "czasownik",
        "example": {
          "target": "Tražim vodu.",
          "source": "Szukam wody."
        }
      },
      {
        "id": "word-6",
        "stage": "words",
        "type": "word",
        "target": "imati",
        "source": "mieć",
        "partOfSpeech": "czasownik",
        "example": {
          "target": "Imate li ovo u drugoj veličini?",
          "source": "Czy mają Państwo to w innym rozmiarze?"
        }
      },
      {
        "id": "check-2",
        "stage": "words",
        "type": "choice",
        "instruction": "Jak powiesz to po chorwacku?",
        "prompt": "szukać / prosić o",
        "options": [
          "veličina",
          "tražiti",
          "kupiti"
        ],
        "correctIndex": 1,
        "targetText": "options"
      },
      {
        "id": "word-7",
        "stage": "words",
        "type": "word",
        "target": "veličina",
        "source": "rozmiar",
        "partOfSpeech": "rzeczownik",
        "example": {
          "target": "Imate li ovo u drugoj veličini?",
          "source": "Czy mają Państwo to w innym rozmiarze?"
        }
      },
      {
        "id": "word-8",
        "stage": "words",
        "type": "word",
        "target": "kartica",
        "source": "karta płatnicza",
        "partOfSpeech": "rzeczownik",
        "example": {
          "target": "Mogu li platiti karticom?",
          "source": "Czy mogę zapłacić kartą?"
        }
      },
      {
        "id": "check-3",
        "stage": "words",
        "type": "choice",
        "instruction": "Co znaczy to słowo?",
        "prompt": "veličina",
        "options": [
          "kupić",
          "mieć",
          "rozmiar"
        ],
        "correctIndex": 2,
        "targetText": "prompt"
      },
      {
        "id": "structure",
        "stage": "structure",
        "type": "structure",
        "title": "Koliko košta?",
        "explanation": "O cenę pytasz Koliko ovo košta? — ile to kosztuje? Po liczbie mówisz eura: deset eura. Gdy czegoś szukasz, mówisz Tražim… albo Želim kupiti…, a rzeczownik żeński znów dostaje -u: knjiga → ovu knjigu.",
        "examples": [
          {
            "target": "Koliko ovo košta?",
            "source": "Ile to kosztuje?"
          },
          {
            "target": "Košta deset eura.",
            "source": "Kosztuje dziesięć euro."
          },
          {
            "target": "Želim kupiti ovu knjigu.",
            "source": "Chcę kupić tę książkę."
          }
        ]
      },
      {
        "id": "gap",
        "stage": "structure",
        "type": "gap",
        "instruction": "Uzupełnij lukę.",
        "before": "Košta deset",
        "after": ".",
        "accepted": [
          "eura"
        ],
        "translation": "Kosztuje dziesięć euro."
      },
      {
        "id": "translate-1",
        "stage": "practice",
        "type": "translate",
        "instruction": "Przetłumacz na chorwacki.",
        "prompt": "Ile to kosztuje?",
        "accepted": [
          "Koliko ovo košta?",
          "Koliko to košta?"
        ]
      },
      {
        "id": "order",
        "stage": "practice",
        "type": "order",
        "instruction": "Ułóż zdanie.",
        "translation": "Chcę kupić tę książkę.",
        "tokens": [
          "kupiti",
          "knjigu",
          "ovu",
          "želim"
        ],
        "accepted": [
          "Želim kupiti ovu knjigu."
        ]
      },
      {
        "id": "comprehend",
        "stage": "practice",
        "type": "choice",
        "instruction": "Co znaczy to zdanie?",
        "prompt": "Imate li ovo u drugoj veličini?",
        "options": [
          "Czy mają Państwo to w innym rozmiarze?",
          "Ile to kosztuje?",
          "Kosztuje dziesięć euro."
        ],
        "correctIndex": 0,
        "targetText": "prompt"
      },
      {
        "id": "translate-2",
        "stage": "practice",
        "type": "translate",
        "instruction": "Przetłumacz na chorwacki.",
        "prompt": "Czy mogę zapłacić kartą?",
        "accepted": [
          "Mogu li platiti karticom?"
        ]
      },
      {
        "id": "listening",
        "stage": "dialog",
        "type": "listening",
        "instruction": "Posłuchaj dialogu i odpowiedz na pytanie.",
        "title": "W sklepie",
        "lines": [
          {
            "speaker": "Marko",
            "text": "Oprostite, gdje je mlijeko?",
            "translation": "Przepraszam, gdzie jest mleko?",
            "audio": "/audio/listening/hr-a1/a1-trgovina/01-marko.mp3"
          },
          {
            "speaker": "Ana",
            "text": "Tamo, pored kruha.",
            "translation": "Tam, obok chleba.",
            "audio": "/audio/listening/hr-a1/a1-trgovina/02-ana.mp3"
          },
          {
            "speaker": "Marko",
            "text": "A gdje su jaja?",
            "translation": "A gdzie są jajka?",
            "audio": "/audio/listening/hr-a1/a1-trgovina/03-marko.mp3"
          },
          {
            "speaker": "Ana",
            "text": "Jaja su u hladnjaku, s desne strane.",
            "translation": "Jajka są w lodówce, po prawej stronie.",
            "audio": "/audio/listening/hr-a1/a1-trgovina/04-ana.mp3"
          },
          {
            "speaker": "Marko",
            "text": "Hvala na pomoći.",
            "translation": "Dziękuję za pomoc.",
            "audio": "/audio/listening/hr-a1/a1-trgovina/05-marko.mp3"
          }
        ],
        "questions": [
          {
            "prompt": "Gdzie jest mleko?",
            "options": [
              "Obok chleba",
              "W lodówce",
              "Przy kasie"
            ],
            "correctIndex": 0
          }
        ]
      },
      {
        "id": "dialog",
        "stage": "dialog",
        "type": "dialog",
        "title": "W sklepie",
        "turns": [
          {
            "kind": "line",
            "line": {
              "speaker": "Prodavačica",
              "text": "Dobar dan. Izvolite?",
              "translation": "Dzień dobry. W czym mogę pomóc?"
            }
          },
          {
            "kind": "reply",
            "prompt": "Powiedz, że szukasz wody.",
            "accepted": [
              "Tražim vodu."
            ],
            "pattern": "^(dobar dan )?tražim (vodu|kruh|sir|kavu|knjigu|telefon)$",
            "suggestion": "Tražim vodu."
          },
          {
            "kind": "line",
            "line": {
              "speaker": "Prodavačica",
              "text": "Izvolite.",
              "translation": "Proszę."
            }
          },
          {
            "kind": "reply",
            "prompt": "Zapytaj o cenę.",
            "accepted": [
              "Koliko ovo košta?",
              "Koliko to košta?"
            ],
            "suggestion": "Koliko ovo košta?"
          },
          {
            "kind": "line",
            "line": {
              "speaker": "Prodavačica",
              "text": "Košta deset eura.",
              "translation": "Kosztuje dziesięć euro."
            }
          },
          {
            "kind": "reply",
            "prompt": "Zapytaj, czy możesz zapłacić kartą.",
            "accepted": [
              "Mogu li platiti karticom?"
            ],
            "suggestion": "Mogu li platiti karticom?"
          }
        ]
      },
      {
        "id": "free",
        "stage": "dialog",
        "type": "free",
        "instruction": "Napisz, czego szukasz w sklepie, i zapytaj o cenę.",
        "points": [
          "czego szukasz",
          "pytanie o cenę"
        ],
        "keywords": [
          {
            "any": [
              "tražim",
              "želim",
              "kupiti"
            ],
            "label": "czego szukasz"
          },
          {
            "any": [
              "koliko",
              "košta"
            ],
            "label": "pytanie o cenę"
          }
        ],
        "minSentences": 2,
        "sample": "Tražim vodu. Koliko ovo košta?"
      },
      {
        "id": "summary",
        "stage": "summary",
        "type": "summary",
        "title": "Lekcja ukończona",
        "recap": [
          {
            "target": "Koliko ovo košta?",
            "source": "Ile to kosztuje?"
          },
          {
            "target": "Košta deset eura.",
            "source": "Kosztuje dziesięć euro."
          },
          {
            "target": "Imate li ovo u drugoj veličini?",
            "source": "Czy mają Państwo to w innym rozmiarze?"
          },
          {
            "target": "Tražim vodu.",
            "source": "Szukam wody."
          }
        ]
      }
    ]
  },
  material: {
    "sourceLessonId": "a1-24",
    "grammarFocus": "Koliko košta?; Imate li...?; liczebniki i ilości w prostych frazach",
    "communicativeGoal": "Zapytać o cenę i poprosić o produkt.",
    "sources": [
      "https://www.coe.int/en/web/common-European-framework-reference-languages/table-1-cefr-3.3-common-reference-levels-global-scale",
      "https://www.coe.int/en/web/common-european-framework-reference-languages/cefr-descriptors-search",
      "https://croaticum.ffzg.unizg.hr/?page_id=1106",
      "https://a1.ffzg.unizg.hr/"
    ],
    "records": [
      {
        "recordId": "A1-0415",
        "type": "lesson",
        "sequence": 0,
        "hr": "",
        "pl": "",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "",
        "acceptedAnswers": [],
        "notes": "Projekt autorski oparty na deskryptorach CEFR A1 oraz zakresie początkujących kursów Croaticum. Treści nie są kopią podręcznika.",
        "tags": [
          "curriculum",
          "cefr-a1",
          "croatian"
        ]
      },
      {
        "recordId": "A1-0416",
        "type": "vocabulary",
        "sequence": 1,
        "hr": "koštati",
        "pl": "kosztować",
        "lemma": "koštati",
        "partOfSpeech": "verb",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "koštati"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A1-0417",
        "type": "vocabulary",
        "sequence": 2,
        "hr": "cijena",
        "pl": "cena",
        "lemma": "cijena",
        "partOfSpeech": "noun",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "cijena"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A1-0418",
        "type": "vocabulary",
        "sequence": 3,
        "hr": "euro",
        "pl": "euro",
        "lemma": "euro",
        "partOfSpeech": "noun",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "euro"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A1-0419",
        "type": "vocabulary",
        "sequence": 4,
        "hr": "kupiti",
        "pl": "kupić",
        "lemma": "kupiti",
        "partOfSpeech": "verb",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "kupiti"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A1-0420",
        "type": "vocabulary",
        "sequence": 5,
        "hr": "tražiti",
        "pl": "szukać / prosić o",
        "lemma": "tražiti",
        "partOfSpeech": "verb",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "tražiti"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A1-0421",
        "type": "vocabulary",
        "sequence": 6,
        "hr": "imati",
        "pl": "mieć",
        "lemma": "imati",
        "partOfSpeech": "verb",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "imati"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A1-0422",
        "type": "vocabulary",
        "sequence": 7,
        "hr": "veličina",
        "pl": "rozmiar",
        "lemma": "veličina",
        "partOfSpeech": "noun",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "veličina"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A1-0423",
        "type": "vocabulary",
        "sequence": 8,
        "hr": "kartica",
        "pl": "karta płatnicza",
        "lemma": "kartica",
        "partOfSpeech": "noun",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "kartica"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A1-0424",
        "type": "sentence",
        "sequence": 1,
        "hr": "Koliko ovo košta?",
        "pl": "Ile to kosztuje?",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "Koliko ovo košta?"
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych warto akceptować brak części znaków diakrytycznych jako soft error, ale pokazać poprawną pisownię.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A1-0425",
        "type": "sentence",
        "sequence": 2,
        "hr": "Košta deset eura.",
        "pl": "Kosztuje dziesięć euro.",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "Košta deset eura."
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych warto akceptować brak części znaków diakrytycznych jako soft error, ale pokazać poprawną pisownię.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A1-0426",
        "type": "sentence",
        "sequence": 3,
        "hr": "Imate li ovo u drugoj veličini?",
        "pl": "Czy mają Państwo to w innym rozmiarze?",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "Imate li ovo u drugoj veličini?"
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych warto akceptować brak części znaków diakrytycznych jako soft error, ale pokazać poprawną pisownię.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A1-0427",
        "type": "sentence",
        "sequence": 4,
        "hr": "Tražim vodu.",
        "pl": "Szukam wody.",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "Tražim vodu."
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych warto akceptować brak części znaków diakrytycznych jako soft error, ale pokazać poprawną pisownię.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A1-0428",
        "type": "sentence",
        "sequence": 5,
        "hr": "Želim kupiti ovu knjigu.",
        "pl": "Chcę kupić tę książkę.",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "Želim kupiti ovu knjigu."
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych warto akceptować brak części znaków diakrytycznych jako soft error, ale pokazać poprawną pisownię.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A1-0429",
        "type": "sentence",
        "sequence": 6,
        "hr": "Mogu li platiti karticom?",
        "pl": "Czy mogę zapłacić kartą?",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "Mogu li platiti karticom?"
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych warto akceptować brak części znaków diakrytycznych jako soft error, ale pokazać poprawną pisownię.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A1-0430",
        "type": "exercise_blueprint",
        "sequence": 1,
        "hr": "",
        "pl": "",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "multiple_choice",
        "acceptedAnswers": [],
        "notes": "Wybierz poprawne znaczenie lub odpowiedź do krótkiego promptu.",
        "tags": [
          "exercise",
          "lesson-player"
        ]
      },
      {
        "recordId": "A1-0431",
        "type": "exercise_blueprint",
        "sequence": 2,
        "hr": "",
        "pl": "",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation",
        "acceptedAnswers": [],
        "notes": "Przetłumacz 1 krótkie zdanie PL→HR, akceptując poprawne warianty.",
        "tags": [
          "exercise",
          "lesson-player"
        ]
      },
      {
        "recordId": "A1-0432",
        "type": "exercise_blueprint",
        "sequence": 3,
        "hr": "",
        "pl": "",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "free_response",
        "acceptedAnswers": [],
        "notes": "Napisz 1–2 własne zdania z materiałem lekcji; oceń sens i kluczową konstrukcję.",
        "tags": [
          "exercise",
          "lesson-player"
        ]
      }
    ]
  },
};
