// AUTO-GENERATED by scripts/generate-a1-curriculum.mjs — nie edytuj ręcznie.
// a1-03-02 · Praca i nauka
// Źródło: curriculum/hr-a1/lexodromia_hr_A1_curriculum.csv (sha256 75adf749ae368f10…) + didactics.json
import type { GeneratedLesson } from "../../../types";

export const LESSON: GeneratedLesson = {
  content: {
    "lessonId": "a1-03-02",
    "vocabulary": [
      {
        "target": "učiti",
        "source": "uczyć się",
        "lemma": "učiti",
        "partOfSpeech": "verb",
        "recordId": "A1-0200"
      },
      {
        "target": "studirati",
        "source": "studiować",
        "lemma": "studirati",
        "partOfSpeech": "verb",
        "recordId": "A1-0201"
      },
      {
        "target": "ured",
        "source": "biuro",
        "lemma": "ured",
        "partOfSpeech": "noun",
        "recordId": "A1-0202"
      },
      {
        "target": "škola",
        "source": "szkoła",
        "lemma": "škola",
        "partOfSpeech": "noun",
        "recordId": "A1-0203"
      },
      {
        "target": "fakultet",
        "source": "uczelnia / wydział",
        "lemma": "fakultet",
        "partOfSpeech": "noun",
        "recordId": "A1-0204"
      },
      {
        "target": "kod kuće",
        "source": "w domu",
        "lemma": "kod kuće",
        "partOfSpeech": "phrase",
        "recordId": "A1-0205"
      },
      {
        "target": "računalo",
        "source": "komputer",
        "lemma": "računalo",
        "partOfSpeech": "noun",
        "recordId": "A1-0206"
      },
      {
        "target": "hrvatski",
        "source": "chorwacki",
        "lemma": "hrvatski",
        "partOfSpeech": "adjective",
        "recordId": "A1-0207"
      }
    ],
    "steps": [
      {
        "id": "intro",
        "stage": "intro",
        "type": "intro",
        "title": "Praca i nauka",
        "body": "Po tej lekcji będziesz umieć powiedzieć, gdzie pracujesz i czego się uczysz.",
        "goalsTitle": "Powiesz między innymi",
        "goals": [
          {
            "target": "Radim od kuće.",
            "source": "Pracuję z domu."
          },
          {
            "target": "Radim u uredu.",
            "source": "Pracuję w biurze."
          },
          {
            "target": "Učim hrvatski svaki dan.",
            "source": "Uczę się chorwackiego codziennie."
          }
        ]
      },
      {
        "id": "word-1",
        "stage": "words",
        "type": "word",
        "target": "učiti",
        "source": "uczyć się",
        "partOfSpeech": "czasownik",
        "example": {
          "target": "Učim hrvatski svaki dan.",
          "source": "Uczę się chorwackiego codziennie."
        }
      },
      {
        "id": "word-2",
        "stage": "words",
        "type": "word",
        "target": "studirati",
        "source": "studiować",
        "partOfSpeech": "czasownik",
        "example": {
          "target": "Studiram u Zagrebu.",
          "source": "Studiuję w Zagrzebiu."
        }
      },
      {
        "id": "word-3",
        "stage": "words",
        "type": "word",
        "target": "ured",
        "source": "biuro",
        "partOfSpeech": "rzeczownik",
        "example": {
          "target": "Radim u uredu.",
          "source": "Pracuję w biurze."
        }
      },
      {
        "id": "check-1",
        "stage": "words",
        "type": "choice",
        "instruction": "Co znaczy to słowo?",
        "prompt": "učiti",
        "options": [
          "uczyć się",
          "komputer",
          "szkoła"
        ],
        "correctIndex": 0,
        "targetText": "prompt"
      },
      {
        "id": "word-4",
        "stage": "words",
        "type": "word",
        "target": "škola",
        "source": "szkoła",
        "partOfSpeech": "rzeczownik"
      },
      {
        "id": "word-5",
        "stage": "words",
        "type": "word",
        "target": "fakultet",
        "source": "uczelnia / wydział",
        "partOfSpeech": "rzeczownik"
      },
      {
        "id": "word-6",
        "stage": "words",
        "type": "word",
        "target": "kod kuće",
        "source": "w domu",
        "partOfSpeech": "zwrot"
      },
      {
        "id": "check-2",
        "stage": "words",
        "type": "choice",
        "instruction": "Jak powiesz to po chorwacku?",
        "prompt": "uczelnia / wydział",
        "options": [
          "škola",
          "fakultet",
          "učiti"
        ],
        "correctIndex": 1,
        "targetText": "options"
      },
      {
        "id": "word-7",
        "stage": "words",
        "type": "word",
        "target": "računalo",
        "source": "komputer",
        "partOfSpeech": "rzeczownik",
        "example": {
          "target": "Radim na računalu.",
          "source": "Pracuję na komputerze."
        }
      },
      {
        "id": "word-8",
        "stage": "words",
        "type": "word",
        "target": "hrvatski",
        "source": "chorwacki",
        "partOfSpeech": "przymiotnik",
        "example": {
          "target": "Učim hrvatski svaki dan.",
          "source": "Uczę się chorwackiego codziennie."
        }
      },
      {
        "id": "check-3",
        "stage": "words",
        "type": "choice",
        "instruction": "Co znaczy to słowo?",
        "prompt": "računalo",
        "options": [
          "chorwacki",
          "studiować",
          "komputer"
        ],
        "correctIndex": 2,
        "targetText": "prompt"
      },
      {
        "id": "structure",
        "stage": "structure",
        "type": "structure",
        "title": "Gdje radiš?",
        "explanation": "Na pytanie „gdzie?” odpowiadasz przez u i zmienioną końcówkę — tak jak po polsku: ured → u uredu (w biurze), Zagreb → u Zagrebu. Na razie ucz się tych zwrotów w całości. Dwa wyjątki do zapamiętania: kod kuće — w domu, od kuće — z domu.",
        "examples": [
          {
            "target": "Radim u uredu.",
            "source": "Pracuję w biurze."
          },
          {
            "target": "Studiram u Zagrebu.",
            "source": "Studiuję w Zagrzebiu."
          },
          {
            "target": "Radim od kuće.",
            "source": "Pracuję z domu."
          }
        ]
      },
      {
        "id": "gap",
        "stage": "structure",
        "type": "gap",
        "instruction": "Uzupełnij lukę.",
        "before": "Radim u",
        "after": ".",
        "accepted": [
          "uredu"
        ],
        "translation": "Pracuję w biurze."
      },
      {
        "id": "translate-1",
        "stage": "practice",
        "type": "translate",
        "instruction": "Przetłumacz na chorwacki.",
        "prompt": "Dziś nie pracuję.",
        "accepted": [
          "Danas ne radim.",
          "Ne radim danas."
        ]
      },
      {
        "id": "order",
        "stage": "practice",
        "type": "order",
        "instruction": "Ułóż zdanie.",
        "translation": "Uczę się chorwackiego codziennie.",
        "tokens": [
          "svaki",
          "dan",
          "hrvatski",
          "učim"
        ],
        "accepted": [
          "Učim hrvatski svaki dan."
        ]
      },
      {
        "id": "comprehend",
        "stage": "practice",
        "type": "choice",
        "instruction": "Co znaczy to zdanie?",
        "prompt": "Radim na računalu.",
        "options": [
          "Pracuję na komputerze.",
          "Pracuję z domu.",
          "Pracuję w biurze."
        ],
        "correctIndex": 0,
        "targetText": "prompt"
      },
      {
        "id": "dialog",
        "stage": "dialog",
        "type": "dialog",
        "title": "Praca i nauka",
        "turns": [
          {
            "kind": "line",
            "line": {
              "speaker": "Ana",
              "text": "Gdje radiš?",
              "translation": "Gdzie pracujesz?"
            }
          },
          {
            "kind": "reply",
            "prompt": "Powiedz, gdzie pracujesz.",
            "accepted": [
              "Radim u uredu.",
              "Radim od kuće."
            ],
            "pattern": "^(ja )?radim (u \\p{L}+|od kuće|kod kuće)$",
            "suggestion": "Radim u uredu."
          },
          {
            "kind": "line",
            "line": {
              "speaker": "Ana",
              "text": "Što učiš?",
              "translation": "Czego się uczysz?"
            }
          },
          {
            "kind": "reply",
            "prompt": "Powiedz, że uczysz się chorwackiego.",
            "accepted": [
              "Učim hrvatski svaki dan.",
              "Učim hrvatski."
            ],
            "pattern": "^(ja )?učim hrvatski( svaki dan)?$",
            "suggestion": "Učim hrvatski svaki dan."
          }
        ]
      },
      {
        "id": "free",
        "stage": "dialog",
        "type": "free",
        "instruction": "Napisz, gdzie pracujesz lub się uczysz.",
        "points": [
          "praca albo nauka",
          "miejsce"
        ],
        "keywords": [
          {
            "any": [
              "radim",
              "studiram",
              "učim"
            ],
            "label": "praca lub nauka"
          },
          {
            "any": [
              "u",
              "od",
              "kod"
            ],
            "label": "miejsce (u … / od kuće)"
          }
        ],
        "minSentences": 2,
        "sample": "Radim u uredu. Učim hrvatski svaki dan."
      },
      {
        "id": "summary",
        "stage": "summary",
        "type": "summary",
        "title": "Lekcja ukończona",
        "recap": [
          {
            "target": "Radim od kuće.",
            "source": "Pracuję z domu."
          },
          {
            "target": "Radim u uredu.",
            "source": "Pracuję w biurze."
          },
          {
            "target": "Učim hrvatski svaki dan.",
            "source": "Uczę się chorwackiego codziennie."
          },
          {
            "target": "Studiram u Zagrebu.",
            "source": "Studiuję w Zagrzebiu."
          }
        ]
      }
    ]
  },
  material: {
    "sourceLessonId": "a1-12",
    "grammarFocus": "raditi/učiti/studirati; u + miejscownik w gotowych frazach",
    "communicativeGoal": "Powiedzieć, gdzie pracujesz i czego się uczysz.",
    "sources": [
      "https://www.coe.int/en/web/common-European-framework-reference-languages/table-1-cefr-3.3-common-reference-levels-global-scale",
      "https://www.coe.int/en/web/common-european-framework-reference-languages/cefr-descriptors-search",
      "https://croaticum.ffzg.unizg.hr/?page_id=1106",
      "https://a1.ffzg.unizg.hr/",
      "https://www.easy-croatian.com/2014/11/15.html",
      "https://www.easy-croatian.com/2014/11/6.html",
      "https://www.easy-croatian.com/2014/11/a4.html"
    ],
    "records": [
      {
        "recordId": "A1-0199",
        "type": "lesson",
        "sequence": 0,
        "hr": "",
        "pl": "",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "",
        "acceptedAnswers": [],
        "notes": "Projekt autorski oparty na deskryptorach CEFR A1 oraz zakresie początkujących kursów Croaticum. Treści nie są kopią podręcznika.",
        "tags": [
          "curriculum",
          "cefr-a1",
          "croatian"
        ]
      },
      {
        "recordId": "A1-0200",
        "type": "vocabulary",
        "sequence": 1,
        "hr": "učiti",
        "pl": "uczyć się",
        "lemma": "učiti",
        "partOfSpeech": "verb",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "učiti"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A1-0201",
        "type": "vocabulary",
        "sequence": 2,
        "hr": "studirati",
        "pl": "studiować",
        "lemma": "studirati",
        "partOfSpeech": "verb",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "studirati"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A1-0202",
        "type": "vocabulary",
        "sequence": 3,
        "hr": "ured",
        "pl": "biuro",
        "lemma": "ured",
        "partOfSpeech": "noun",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "ured"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A1-0203",
        "type": "vocabulary",
        "sequence": 4,
        "hr": "škola",
        "pl": "szkoła",
        "lemma": "škola",
        "partOfSpeech": "noun",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "škola"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A1-0204",
        "type": "vocabulary",
        "sequence": 5,
        "hr": "fakultet",
        "pl": "uczelnia / wydział",
        "lemma": "fakultet",
        "partOfSpeech": "noun",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "fakultet"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A1-0205",
        "type": "vocabulary",
        "sequence": 6,
        "hr": "kod kuće",
        "pl": "w domu",
        "lemma": "kod kuće",
        "partOfSpeech": "phrase",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "kod kuće"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A1-0206",
        "type": "vocabulary",
        "sequence": 7,
        "hr": "računalo",
        "pl": "komputer",
        "lemma": "računalo",
        "partOfSpeech": "noun",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "računalo"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A1-0207",
        "type": "vocabulary",
        "sequence": 8,
        "hr": "hrvatski",
        "pl": "chorwacki",
        "lemma": "hrvatski",
        "partOfSpeech": "adjective",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "hrvatski"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A1-0208",
        "type": "sentence",
        "sequence": 1,
        "hr": "Radim od kuće.",
        "pl": "Pracuję z domu.",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "Radim od kuće."
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych warto akceptować brak części znaków diakrytycznych jako soft error, ale pokazać poprawną pisownię.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A1-0209",
        "type": "sentence",
        "sequence": 2,
        "hr": "Radim u uredu.",
        "pl": "Pracuję w biurze.",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "Radim u uredu."
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych warto akceptować brak części znaków diakrytycznych jako soft error, ale pokazać poprawną pisownię.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A1-0210",
        "type": "sentence",
        "sequence": 3,
        "hr": "Učim hrvatski svaki dan.",
        "pl": "Uczę się chorwackiego codziennie.",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "Učim hrvatski svaki dan."
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych warto akceptować brak części znaków diakrytycznych jako soft error, ale pokazać poprawną pisownię.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A1-0211",
        "type": "sentence",
        "sequence": 4,
        "hr": "Studiram u Zagrebu.",
        "pl": "Studiuję w Zagrzebiu.",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "Studiram u Zagrebu."
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych warto akceptować brak części znaków diakrytycznych jako soft error, ale pokazać poprawną pisownię.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A1-0212",
        "type": "sentence",
        "sequence": 5,
        "hr": "Radim na računalu.",
        "pl": "Pracuję na komputerze.",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "Radim na računalu."
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych warto akceptować brak części znaków diakrytycznych jako soft error, ale pokazać poprawną pisownię.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A1-0213",
        "type": "sentence",
        "sequence": 6,
        "hr": "Danas ne radim.",
        "pl": "Dziś nie pracuję.",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "Danas ne radim."
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych warto akceptować brak części znaków diakrytycznych jako soft error, ale pokazać poprawną pisownię.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A1-0214",
        "type": "exercise_blueprint",
        "sequence": 1,
        "hr": "",
        "pl": "",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "multiple_choice",
        "acceptedAnswers": [],
        "notes": "Wybierz poprawne znaczenie lub odpowiedź do krótkiego promptu.",
        "tags": [
          "exercise",
          "lesson-player"
        ]
      },
      {
        "recordId": "A1-0215",
        "type": "exercise_blueprint",
        "sequence": 2,
        "hr": "",
        "pl": "",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation",
        "acceptedAnswers": [],
        "notes": "Przetłumacz 1 krótkie zdanie PL→HR, akceptując poprawne warianty.",
        "tags": [
          "exercise",
          "lesson-player"
        ]
      },
      {
        "recordId": "A1-0216",
        "type": "exercise_blueprint",
        "sequence": 3,
        "hr": "",
        "pl": "",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "free_response",
        "acceptedAnswers": [],
        "notes": "Napisz 1–2 własne zdania z materiałem lekcji; oceń sens i kluczową konstrukcję.",
        "tags": [
          "exercise",
          "lesson-player"
        ]
      }
    ]
  },
};
