// AUTO-GENERATED by scripts/generate-a1-curriculum.mjs — nie edytuj ręcznie.
// a1-01-05 · Powtórka: pierwsza rozmowa
// Źródło: curriculum/hr-a1/lexodromia_hr_A1_curriculum.csv (sha256 ba0474dcbdcbe04e…) + didactics.json
import type { GeneratedLesson } from "../../../types";

export const LESSON: GeneratedLesson = {
  content: {
    "lessonId": "a1-01-05",
    "vocabulary": [
      {
        "target": "ponoviti",
        "source": "powtórzyć",
        "lemma": "ponoviti",
        "partOfSpeech": "verb",
        "recordId": "A1-0074",
        "audioSrc": "/audio/hr/a1/module-01/ponoviti.mp3"
      },
      {
        "target": "razumjeti",
        "source": "rozumieć",
        "lemma": "razumjeti",
        "partOfSpeech": "verb",
        "recordId": "A1-0075",
        "audioSrc": "/audio/hr/a1/module-01/razumjeti.mp3"
      },
      {
        "target": "pitati",
        "source": "pytać",
        "lemma": "pitati",
        "partOfSpeech": "verb",
        "recordId": "A1-0076",
        "audioSrc": "/audio/hr/a1/module-01/pitati.mp3"
      },
      {
        "target": "odgovoriti",
        "source": "odpowiedzieć",
        "lemma": "odgovoriti",
        "partOfSpeech": "verb",
        "recordId": "A1-0077",
        "audioSrc": "/audio/hr/a1/module-01/odgovoriti.mp3"
      },
      {
        "target": "razgovor",
        "source": "rozmowa",
        "lemma": "razgovor",
        "partOfSpeech": "noun",
        "recordId": "A1-0078",
        "audioSrc": "/audio/hr/a1/module-01/razgovor.mp3"
      },
      {
        "target": "još jednom",
        "source": "jeszcze raz",
        "lemma": "još jednom",
        "partOfSpeech": "phrase",
        "recordId": "A1-0079",
        "audioSrc": "/audio/hr/a1/module-01/jos-jednom.mp3"
      },
      {
        "target": "polako",
        "source": "powoli",
        "lemma": "polako",
        "partOfSpeech": "adverb",
        "recordId": "A1-0080",
        "audioSrc": "/audio/hr/a1/module-01/polako.mp3"
      },
      {
        "target": "molim",
        "source": "proszę",
        "lemma": "molim",
        "partOfSpeech": "interjection",
        "recordId": "A1-0081",
        "audioSrc": "/audio/hr/a1/module-01/molim.mp3"
      }
    ],
    "steps": [
      {
        "id": "intro",
        "stage": "intro",
        "type": "intro",
        "title": "Powtórka: pierwsza rozmowa",
        "body": "Powtórka modułu „Pierwsze kroki”. Połączysz materiał z lekcji 1–4 i sprawdzisz go w rozmowie.",
        "goalsTitle": "Sprawdzisz, czy umiesz",
        "goals": [
          "przywitać się, pożegnać i zapytać o samopoczucie",
          "powiedzieć, skąd jesteś i gdzie mieszkasz",
          "przedstawić się i zapytać o imię",
          "podać wiek i rozumieć podstawowe liczby"
        ]
      },
      {
        "id": "recall-1",
        "stage": "words",
        "type": "choice",
        "instruction": "Co znaczy to słowo?",
        "prompt": "odlično",
        "options": [
          "dzień dobry",
          "miasto",
          "świetnie"
        ],
        "correctIndex": 2,
        "targetText": "prompt",
        "promptAudioSrc": "/audio/hr/a1/module-01/odlicno.mp3"
      },
      {
        "id": "recall-2",
        "stage": "words",
        "type": "choice",
        "instruction": "Co znaczy to słowo?",
        "prompt": "odakle",
        "options": [
          "skąd",
          "dziękuję",
          "miło mi"
        ],
        "correctIndex": 0,
        "targetText": "prompt",
        "promptAudioSrc": "/audio/hr/a1/module-01/odakle.mp3"
      },
      {
        "id": "recall-3",
        "stage": "words",
        "type": "choice",
        "instruction": "Co znaczy to słowo?",
        "prompt": "ti",
        "options": [
          "Polska",
          "ty",
          "ja"
        ],
        "correctIndex": 1,
        "targetText": "prompt",
        "promptAudioSrc": "/audio/hr/a1/module-01/ti.mp3"
      },
      {
        "id": "vocab",
        "stage": "words",
        "type": "vocabList",
        "title": "Przydatne słowa na koniec modułu",
        "note": "Nie musisz ich jeszcze znać na pamięć — pojawią się w rozmowie.",
        "items": [
          {
            "target": "ponoviti",
            "source": "powtórzyć",
            "partOfSpeech": "czasownik",
            "audioSrc": "/audio/hr/a1/module-01/ponoviti.mp3"
          },
          {
            "target": "razumjeti",
            "source": "rozumieć",
            "partOfSpeech": "czasownik",
            "audioSrc": "/audio/hr/a1/module-01/razumjeti.mp3"
          },
          {
            "target": "pitati",
            "source": "pytać",
            "partOfSpeech": "czasownik",
            "audioSrc": "/audio/hr/a1/module-01/pitati.mp3"
          },
          {
            "target": "odgovoriti",
            "source": "odpowiedzieć",
            "partOfSpeech": "czasownik",
            "audioSrc": "/audio/hr/a1/module-01/odgovoriti.mp3"
          },
          {
            "target": "razgovor",
            "source": "rozmowa",
            "partOfSpeech": "rzeczownik",
            "audioSrc": "/audio/hr/a1/module-01/razgovor.mp3"
          },
          {
            "target": "još jednom",
            "source": "jeszcze raz",
            "partOfSpeech": "zwrot",
            "audioSrc": "/audio/hr/a1/module-01/jos-jednom.mp3"
          },
          {
            "target": "polako",
            "source": "powoli",
            "partOfSpeech": "przysłówek",
            "audioSrc": "/audio/hr/a1/module-01/polako.mp3"
          },
          {
            "target": "molim",
            "source": "proszę",
            "partOfSpeech": "wykrzyknik",
            "audioSrc": "/audio/hr/a1/module-01/molim.mp3"
          }
        ]
      },
      {
        "id": "gap",
        "stage": "structure",
        "type": "gap",
        "instruction": "Uzupełnij lukę.",
        "before": "",
        "after": "dvadeset šest godina.",
        "accepted": [
          "Imam"
        ],
        "translation": "Mam dwadzieścia sześć lat.",
        "answerAudioSrc": "/audio/hr/a1/module-01/imam-dvadeset-sest-godina.mp3"
      },
      {
        "id": "order",
        "stage": "structure",
        "type": "order",
        "instruction": "Ułóż zdanie.",
        "translation": "Nie mam się zbyt dobrze.",
        "tokens": [
          "baš",
          "dobro",
          "nisam"
        ],
        "accepted": [
          "Nisam baš dobro."
        ],
        "answerAudioSrc": "/audio/hr/a1/module-01/nisam-bas-dobro.mp3"
      },
      {
        "id": "translate-1",
        "stage": "practice",
        "type": "translate",
        "instruction": "Przetłumacz na chorwacki.",
        "prompt": "Mam się świetnie.",
        "accepted": [
          "Odlično sam.",
          "Ja sam odlično."
        ],
        "answerAudioSrc": "/audio/hr/a1/module-01/odlicno-sam.mp3"
      },
      {
        "id": "translate-2",
        "stage": "practice",
        "type": "translate",
        "instruction": "Przetłumacz na chorwacki.",
        "prompt": "Mieszkam w Polsce.",
        "accepted": [
          "Živim u Poljskoj."
        ],
        "answerAudioSrc": "/audio/hr/a1/module-01/zivim-u-poljskoj.mp3"
      },
      {
        "id": "translate-3",
        "stage": "practice",
        "type": "translate",
        "instruction": "Przetłumacz na chorwacki.",
        "prompt": "Ile masz lat?",
        "accepted": [
          "Koliko imaš godina?",
          "Koliko ti imaš godina?"
        ],
        "answerAudioSrc": "/audio/hr/a1/module-01/koliko-imas-godina.mp3"
      },
      {
        "id": "dialog",
        "stage": "dialog",
        "type": "dialog",
        "title": "Pierwsza rozmowa",
        "turns": [
          {
            "kind": "line",
            "line": {
              "speaker": "Ana",
              "text": "Bok! Zovem se Ana.",
              "translation": "Cześć! Mam na imię Ana.",
              "audioSrc": "/audio/hr/a1/module-01/bok-zovem-se-ana.mp3"
            }
          },
          {
            "kind": "reply",
            "prompt": "Przedstaw się.",
            "accepted": [
              "Bok! Zovem se Michał."
            ],
            "pattern": "^(bok )?(ja )?zovem se \\p{L}+( \\p{L}+)?$",
            "suggestion": "Bok! Zovem se Michał.",
            "suggestionAudioSrc": "/audio/hr/a1/module-01/bok-zovem-se-michal.mp3"
          },
          {
            "kind": "line",
            "line": {
              "speaker": "Ana",
              "text": "Odakle si?",
              "translation": "Skąd jesteś?",
              "audioSrc": "/audio/hr/a1/module-01/odakle-si.mp3"
            }
          },
          {
            "kind": "reply",
            "prompt": "Powiedz, skąd jesteś.",
            "accepted": [
              "Iz Poljske sam.",
              "Ja sam iz Poljske."
            ],
            "pattern": "^(ja sam )?iz \\p{L}+( sam)?$",
            "suggestion": "Iz Poljske sam.",
            "suggestionAudioSrc": "/audio/hr/a1/module-01/iz-poljske-sam.mp3"
          },
          {
            "kind": "line",
            "line": {
              "speaker": "Ana",
              "text": "Gdje živiš?",
              "translation": "Gdzie mieszkasz?",
              "audioSrc": "/audio/hr/a1/module-01/gdje-zivis.mp3"
            }
          },
          {
            "kind": "reply",
            "prompt": "Powiedz, gdzie mieszkasz.",
            "accepted": [
              "Živim u Poljskoj."
            ],
            "pattern": "^(ja )?živim u \\p{L}+$",
            "suggestion": "Živim u Poljskoj.",
            "suggestionAudioSrc": "/audio/hr/a1/module-01/zivim-u-poljskoj.mp3"
          },
          {
            "kind": "line",
            "line": {
              "speaker": "Ana",
              "text": "Koliko imaš godina?",
              "translation": "Ile masz lat?",
              "audioSrc": "/audio/hr/a1/module-01/koliko-imas-godina.mp3"
            }
          },
          {
            "kind": "reply",
            "prompt": "Podaj swój wiek.",
            "accepted": [
              "Imam dvadeset šest godina."
            ],
            "pattern": "^(ja )?imam [\\p{L} ]+ godin[aue]$",
            "suggestion": "Imam dvadeset šest godina.",
            "suggestionAudioSrc": "/audio/hr/a1/module-01/imam-dvadeset-sest-godina.mp3"
          },
          {
            "kind": "line",
            "line": {
              "speaker": "Ana",
              "text": "Ja imam dvadeset pet godina.",
              "translation": "Ja mam dwadzieścia pięć lat.",
              "audioSrc": "/audio/hr/a1/module-01/ja-imam-dvadeset-pet-godina.mp3"
            }
          },
          {
            "kind": "reply",
            "prompt": "Nie dosłyszałeś — poproś, żeby Ana powtórzyła.",
            "accepted": [
              "Možeš li ponoviti, molim?",
              "Možeš li ponoviti?"
            ],
            "pattern": "^(možeš li )?(to )?ponoviti( molim)?$|^još jednom( molim)?$",
            "suggestion": "Možeš li ponoviti, molim?",
            "suggestionAudioSrc": "/audio/hr/a1/module-01/mozes-li-ponoviti-molim.mp3"
          }
        ]
      },
      {
        "id": "can-do",
        "stage": "dialog",
        "type": "free",
        "instruction": "Przedstaw się w 2–4 zdaniach.",
        "points": [
          "jak masz na imię",
          "skąd jesteś i gdzie mieszkasz",
          "ile masz lat"
        ],
        "keywords": [
          {
            "any": [
              "zovem"
            ],
            "label": "imię"
          },
          {
            "any": [
              "iz"
            ],
            "label": "pochodzenie"
          },
          {
            "any": [
              "živim",
              "zivim"
            ],
            "label": "miejsce zamieszkania"
          },
          {
            "any": [
              "imam"
            ],
            "label": "wiek"
          }
        ],
        "minSentences": 2,
        "sample": "Zovem se Michał. Iz Poljske sam. Živim u Krakovu. Imam dvadeset šest godina.",
        "sampleAudioSrc": "/audio/hr/a1/module-01/zovem-se-michal-iz-poljske-sam-zivim-u-krakovu-imam-dvadeset.mp3"
      },
      {
        "id": "summary",
        "stage": "summary",
        "type": "summary",
        "title": "Lekcja ukończona",
        "recap": [
          {
            "target": "Bok! Zovem se Ana.",
            "source": "Cześć! Mam na imię Ana.",
            "audioSrc": "/audio/hr/a1/module-01/bok-zovem-se-ana.mp3"
          },
          {
            "target": "Odakle si?",
            "source": "Skąd jesteś?",
            "audioSrc": "/audio/hr/a1/module-01/odakle-si.mp3"
          },
          {
            "target": "Iz Poljske sam.",
            "source": "Jestem z Polski.",
            "audioSrc": "/audio/hr/a1/module-01/iz-poljske-sam.mp3"
          },
          {
            "target": "Gdje živiš?",
            "source": "Gdzie mieszkasz?",
            "audioSrc": "/audio/hr/a1/module-01/gdje-zivis.mp3"
          }
        ],
        "canDo": [
          "przywitać się, pożegnać i zapytać o samopoczucie",
          "powiedzieć, skąd jesteś i gdzie mieszkasz",
          "przedstawić się i zapytać o imię",
          "podać wiek i rozumieć podstawowe liczby"
        ]
      }
    ]
  },
  material: {
    "sourceLessonId": "a1-05",
    "grammarFocus": "utrwalenie biti, imati, zvati se, odakle/gdje",
    "communicativeGoal": "Połączyć materiał modułu w krótką rozmowę.",
    "sources": [
      "https://www.coe.int/en/web/common-European-framework-reference-languages/table-1-cefr-3.3-common-reference-levels-global-scale",
      "https://www.coe.int/en/web/common-european-framework-reference-languages/cefr-descriptors-search",
      "https://croaticum.ffzg.unizg.hr/?page_id=1106",
      "https://a1.ffzg.unizg.hr/"
    ],
    "records": [
      {
        "recordId": "A1-0073",
        "type": "lesson",
        "sequence": 0,
        "hr": "",
        "pl": "",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "",
        "acceptedAnswers": [],
        "notes": "Projekt autorski oparty na deskryptorach CEFR A1 oraz zakresie początkujących kursów Croaticum. Treści nie są kopią podręcznika.",
        "tags": [
          "curriculum",
          "cefr-a1",
          "croatian"
        ]
      },
      {
        "recordId": "A1-0074",
        "type": "vocabulary",
        "sequence": 1,
        "hr": "ponoviti",
        "pl": "powtórzyć",
        "lemma": "ponoviti",
        "partOfSpeech": "verb",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "ponoviti"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A1-0075",
        "type": "vocabulary",
        "sequence": 2,
        "hr": "razumjeti",
        "pl": "rozumieć",
        "lemma": "razumjeti",
        "partOfSpeech": "verb",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "razumjeti"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A1-0076",
        "type": "vocabulary",
        "sequence": 3,
        "hr": "pitati",
        "pl": "pytać",
        "lemma": "pitati",
        "partOfSpeech": "verb",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "pitati"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A1-0077",
        "type": "vocabulary",
        "sequence": 4,
        "hr": "odgovoriti",
        "pl": "odpowiedzieć",
        "lemma": "odgovoriti",
        "partOfSpeech": "verb",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "odgovoriti"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A1-0078",
        "type": "vocabulary",
        "sequence": 5,
        "hr": "razgovor",
        "pl": "rozmowa",
        "lemma": "razgovor",
        "partOfSpeech": "noun",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "razgovor"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A1-0079",
        "type": "vocabulary",
        "sequence": 6,
        "hr": "još jednom",
        "pl": "jeszcze raz",
        "lemma": "još jednom",
        "partOfSpeech": "phrase",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "još jednom"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A1-0080",
        "type": "vocabulary",
        "sequence": 7,
        "hr": "polako",
        "pl": "powoli",
        "lemma": "polako",
        "partOfSpeech": "adverb",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "polako"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A1-0081",
        "type": "vocabulary",
        "sequence": 8,
        "hr": "molim",
        "pl": "proszę",
        "lemma": "molim",
        "partOfSpeech": "interjection",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "molim"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A1-0082",
        "type": "sentence",
        "sequence": 1,
        "hr": "Bok! Zovem se Ana.",
        "pl": "Cześć! Mam na imię Ana.",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "Bok! Zovem se Ana."
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych warto akceptować brak części znaków diakrytycznych jako soft error, ale pokazać poprawną pisownię.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A1-0083",
        "type": "sentence",
        "sequence": 2,
        "hr": "Odakle si?",
        "pl": "Skąd jesteś?",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "Odakle si?"
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych warto akceptować brak części znaków diakrytycznych jako soft error, ale pokazać poprawną pisownię.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A1-0084",
        "type": "sentence",
        "sequence": 3,
        "hr": "Iz Poljske sam.",
        "pl": "Jestem z Polski.",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "Iz Poljske sam."
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych warto akceptować brak części znaków diakrytycznych jako soft error, ale pokazać poprawną pisownię.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A1-0085",
        "type": "sentence",
        "sequence": 4,
        "hr": "Gdje živiš?",
        "pl": "Gdzie mieszkasz?",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "Gdje živiš?"
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych warto akceptować brak części znaków diakrytycznych jako soft error, ale pokazać poprawną pisownię.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A1-0086",
        "type": "sentence",
        "sequence": 5,
        "hr": "Imam dvadeset šest godina.",
        "pl": "Mam dwadzieścia sześć lat.",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "Imam dvadeset šest godina."
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych warto akceptować brak części znaków diakrytycznych jako soft error, ale pokazać poprawną pisownię.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A1-0087",
        "type": "sentence",
        "sequence": 6,
        "hr": "Možeš li ponoviti, molim?",
        "pl": "Czy możesz powtórzyć, proszę?",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "Možeš li ponoviti, molim?"
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych warto akceptować brak części znaków diakrytycznych jako soft error, ale pokazać poprawną pisownię.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A1-0088",
        "type": "exercise_blueprint",
        "sequence": 1,
        "hr": "",
        "pl": "",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "mixed_review",
        "acceptedAnswers": [],
        "notes": "Losuj materiał z 4 poprzednich lekcji: wybór, luka, tłumaczenie, kolejność słów.",
        "tags": [
          "exercise",
          "lesson-player"
        ]
      },
      {
        "recordId": "A1-0089",
        "type": "exercise_blueprint",
        "sequence": 2,
        "hr": "",
        "pl": "",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "dialog_completion",
        "acceptedAnswers": [],
        "notes": "Uzupełnij 3–5 tur dialogu bez podpowiadania pełnych odpowiedzi.",
        "tags": [
          "exercise",
          "lesson-player"
        ]
      },
      {
        "recordId": "A1-0090",
        "type": "exercise_blueprint",
        "sequence": 3,
        "hr": "",
        "pl": "",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "can_do_task",
        "acceptedAnswers": [],
        "notes": "Wykonaj zadanie komunikacyjne modułu w 2–4 zdaniach.",
        "tags": [
          "exercise",
          "lesson-player"
        ]
      }
    ]
  },
};
