#!/usr/bin/env node
/**
 * Nagrania dla Lexodromia Stories — z istniejących nagrań kursu, bez nowej syntezy.
 *
 *   node scripts/stories-audio.mjs            # zapisuje src/stories/data/<historia>/audio.ts
 *   node scripts/stories-audio.mjs --check    # błąd, gdy plik jest nieaktualny (npm test)
 *
 * Wypowiedź dostaje nagranie tylko wtedy, gdy manifest kursu ma DOKŁADNIE ten sam tekst
 * i plik istnieje. Głos (damski / męski) wybiera potem odtwarzacz według postaci,
 * więc Marko nie mówi głosem lektorki. Teksty z {name} nigdy nie mają nagrania.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const require = createRequire(import.meta.url);
const ts = require("typescript");
const CHECK = process.argv.includes("--check");

/** Historie i manifesty nagrań kursu, z których mogą korzystać. */
const STORIES = [{ dir: "split-a1", exportName: "SPLIT_A1", manifests: ["curriculum/hr-a1/audio-manifest.json"] }];

/** Ładuje moduł TS z danymi (bez bundlera): transpilacja + własny require dla ścieżek względnych. */
function loadTs(file, cache = new Map()) {
  if (cache.has(file)) return cache.get(file);
  const { outputText } = ts.transpileModule(readFileSync(file, "utf8"), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020 } });
  const exports = {};
  cache.set(file, exports);
  const req = (id) => {
    if (!id.startsWith(".")) return {};
    const base = resolve(dirname(file), id);
    return loadTs([`${base}.ts`, join(base, "index.ts")].find(existsSync), cache);
  };
  new Function("require", "exports", outputText)(req, exports);
  return exports;
}

const VOICES = { "hr-HR-GabrijelaNeural": "female", "hr-HR-SreckoNeural": "male" };
let stale = 0;
for (const { dir, exportName, manifests } of STORIES) {
  const story = loadTs(join(ROOT, "src/stories/data", dir, "story.ts"))[exportName];
  const recordings = new Map();
  for (const path of manifests) {
    const manifest = JSON.parse(readFileSync(join(ROOT, path), "utf8"));
    for (const item of manifest.items) {
      const voice = VOICES[item.voice];
      if (!voice || !existsSync(join(ROOT, "public", item.audioPath))) continue;
      const entry = recordings.get(item.text) ?? {};
      entry[voice] ??= item.audioPath;
      recordings.set(item.text, entry);
    }
  }
  const texts = new Set();
  for (const mission of story.missions) {
    for (const node of Object.values(mission.dialogue.graph.nodes)) {
      if (node.kind === "say") texts.add(node.text.hr);
      if (node.kind === "choice") node.options.forEach((o) => o.text.hr && texts.add(o.text.hr));
      if (node.kind === "build" || node.kind === "type") texts.add(node.accepted[0]);
    }
  }
  const audio = Object.fromEntries([...texts].filter((t) => !t.includes("{") && recordings.has(t)).sort().map((t) => [t, recordings.get(t)]));
  const body =
    `// AUTO-GENERATED by scripts/stories-audio.mjs — nie edytuj ręcznie.\n` +
    `// Nagrania kursu, których tekst jest dokładnie taki sam jak wypowiedź w historii (${Object.keys(audio).length} z ${texts.size}).\n` +
    `export const ${exportName}_AUDIO: Record<string, { female?: string; male?: string }> = ${JSON.stringify(audio, null, 2)};\n`;
  const out = join(ROOT, "src/stories/data", dir, "audio.ts");
  if (CHECK) {
    if (!existsSync(out) || readFileSync(out, "utf8") !== body) {
      console.error(`Nieaktualne: src/stories/data/${dir}/audio.ts — uruchom: npm run stories:audio`);
      stale++;
    } else console.log(`OK: ${dir} (${Object.keys(audio).length} nagrań z ${texts.size} wypowiedzi)`);
  } else {
    writeFileSync(out, body);
    console.log(`Zapisano src/stories/data/${dir}/audio.ts: ${Object.keys(audio).length} nagrań z ${texts.size} wypowiedzi.`);
  }
}
if (stale) process.exit(1);
