// AUTO-GENERATED by scripts/generate-curriculum.mjs — nie edytuj ręcznie.
// Plan poziomu A2: 2 modułów × 5 lekcji
// Źródło: curriculum/hr-a2/lexodromia_hr_A2_curriculum.csv (sha256 8e24a4c43ceda8b0…) + didactics.json
import type { CourseModule } from "../../types";

export const HR_A2_MODULES: CourseModule[] = [
  {
    "id": "a2-01",
    "levelId": "A2",
    "order": 1,
    "title": "Opowiadam o przeszłości",
    "description": "Opowiadasz o przeszłości: co robiłeś ty i inni, czego nie zrobiłeś, pytasz o podróże i opowiadasz historię po kolei.",
    "canDo": [
      "opowiedzieć, co ty i inni robiliście w weekend",
      "powiedzieć, czego nie zrobiłeś i dlaczego",
      "zapytać kogoś o przeszłość i krótko odpowiedzieć",
      "opowiedzieć krótką historię po kolei"
    ],
    "lessons": [
      {
        "id": "a2-01-01",
        "moduleId": "a2-01",
        "order": 1,
        "title": "Jak minął weekend?",
        "shortDescription": "Opowiedzieć, co ty i inni robiliście w weekend.",
        "estimatedMinutes": 23,
        "status": "not_started",
        "hasContent": true,
        "kind": "lesson",
        "source": {
          "lessonId": "a2-01",
          "grammarFocus": "perfekt: pełna odmiana biti (sam, si, je, smo, ste, su) + imiesłów -o / -la / -li / -le",
          "communicativeGoal": "Opowiedzieć, co ty i inni robiliście w weekend.",
          "sources": [
            "https://www.coe.int/en/web/common-European-framework-reference-languages/table-1-cefr-3.3-common-reference-levels-global-scale",
            "https://www.coe.int/en/web/common-european-framework-reference-languages/cefr-descriptors-search",
            "https://croaticum.ffzg.unizg.hr/?page_id=1106"
          ]
        }
      },
      {
        "id": "a2-01-02",
        "moduleId": "a2-01",
        "order": 2,
        "title": "Nie udało się",
        "shortDescription": "Powiedzieć, czego nie zrobiłeś i dlaczego.",
        "estimatedMinutes": 22,
        "status": "not_started",
        "hasContent": true,
        "kind": "lesson",
        "source": {
          "lessonId": "a2-02",
          "grammarFocus": "przeczenie w perfekcie: nisam, nisi, nije, nismo, niste, nisu + imiesłów; jer (bo); dopełniacz po nemati",
          "communicativeGoal": "Powiedzieć, czego nie zrobiłeś i dlaczego.",
          "sources": [
            "https://www.coe.int/en/web/common-European-framework-reference-languages/table-1-cefr-3.3-common-reference-levels-global-scale",
            "https://www.coe.int/en/web/common-european-framework-reference-languages/cefr-descriptors-search",
            "https://croaticum.ffzg.unizg.hr/?page_id=1106"
          ]
        }
      },
      {
        "id": "a2-01-03",
        "moduleId": "a2-01",
        "order": 3,
        "title": "Byłeś już kiedyś…?",
        "shortDescription": "Zapytać kogoś o przeszłość i krótko odpowiedzieć.",
        "estimatedMinutes": 23,
        "status": "not_started",
        "hasContent": true,
        "kind": "lesson",
        "source": {
          "lessonId": "a2-03",
          "grammarFocus": "pytania w perfekcie: Jesi li bio…?, Je li…?, Jeste li…?; krótkie odpowiedzi Jesam / Nisam; gdje / kada + perfekt; već, još nije",
          "communicativeGoal": "Zapytać kogoś o przeszłość i krótko odpowiedzieć.",
          "sources": [
            "https://www.coe.int/en/web/common-European-framework-reference-languages/table-1-cefr-3.3-common-reference-levels-global-scale",
            "https://www.coe.int/en/web/common-european-framework-reference-languages/cefr-descriptors-search",
            "https://croaticum.ffzg.unizg.hr/?page_id=1106"
          ]
        }
      },
      {
        "id": "a2-01-04",
        "moduleId": "a2-01",
        "order": 4,
        "title": "Historia z podróży",
        "shortDescription": "Opowiedzieć krótką historię po kolei.",
        "estimatedMinutes": 22,
        "status": "not_started",
        "hasContent": true,
        "kind": "lesson",
        "source": {
          "lessonId": "a2-04",
          "grammarFocus": "opowiadanie w perfekcie po kolei: prvo, zatim, onda, poslije, na kraju; prije + dopełniacz (prije dva dana)",
          "communicativeGoal": "Opowiedzieć krótką historię po kolei.",
          "sources": [
            "https://www.coe.int/en/web/common-European-framework-reference-languages/table-1-cefr-3.3-common-reference-levels-global-scale",
            "https://www.coe.int/en/web/common-european-framework-reference-languages/cefr-descriptors-search",
            "https://croaticum.ffzg.unizg.hr/?page_id=1106"
          ]
        }
      },
      {
        "id": "a2-01-05",
        "moduleId": "a2-01",
        "order": 5,
        "title": "Powtórka: opowiadam o przeszłości",
        "shortDescription": "Opowiedzieć o wakacjach: gdzie byłeś, co robiłeś i czego nie zrobiłeś.",
        "estimatedMinutes": 17,
        "status": "not_started",
        "hasContent": true,
        "kind": "review",
        "source": {
          "lessonId": "a2-05",
          "grammarFocus": "utrwalenie perfektu: twierdzenie, przeczenie, pytania, kolejność zdarzeń",
          "communicativeGoal": "Opowiedzieć o wakacjach: gdzie byłeś, co robiłeś i czego nie zrobiłeś.",
          "sources": [
            "https://www.coe.int/en/web/common-European-framework-reference-languages/table-1-cefr-3.3-common-reference-levels-global-scale",
            "https://www.coe.int/en/web/common-european-framework-reference-languages/cefr-descriptors-search",
            "https://croaticum.ffzg.unizg.hr/?page_id=1106"
          ]
        }
      }
    ]
  },
  {
    "id": "a2-02",
    "levelId": "A2",
    "order": 2,
    "title": "Plany i obowiązki",
    "description": "Mówisz o przyszłości: plany twoje i innych, co musisz i możesz, co zrobisz, jeśli…, i umawiasz się ze znajomymi.",
    "canDo": [
      "powiedzieć, co ty i inni zrobicie w najbliższych dniach",
      "powiedzieć, co musisz i co możesz, i poprosić o pozwolenie",
      "powiedzieć, co zrobisz, jeśli coś się wydarzy",
      "zaprosić kogoś, przyjąć albo grzecznie odmówić i ustalić termin"
    ],
    "lessons": [
      {
        "id": "a2-02-01",
        "moduleId": "a2-02",
        "order": 1,
        "title": "Co będziemy robić?",
        "shortDescription": "Powiedzieć, co ty i inni zrobicie w najbliższych dniach.",
        "estimatedMinutes": 23,
        "status": "not_started",
        "hasContent": true,
        "kind": "lesson",
        "source": {
          "lessonId": "a2-06",
          "grammarFocus": "futur I: pełna odmiana ću, ćeš, će, ćemo, ćete, će + bezokolicznik; szyk Radit ćemo / Mi ćemo raditi",
          "communicativeGoal": "Powiedzieć, co ty i inni zrobicie w najbliższych dniach.",
          "sources": [
            "https://www.coe.int/en/web/common-European-framework-reference-languages/table-1-cefr-3.3-common-reference-levels-global-scale",
            "https://www.coe.int/en/web/common-european-framework-reference-languages/cefr-descriptors-search",
            "https://croaticum.ffzg.unizg.hr/?page_id=1106"
          ]
        }
      },
      {
        "id": "a2-02-02",
        "moduleId": "a2-02",
        "order": 2,
        "title": "Muszę, mogę, wolno mi",
        "shortDescription": "Powiedzieć, co musisz i co możesz, i poprosić o pozwolenie.",
        "estimatedMinutes": 23,
        "status": "not_started",
        "hasContent": true,
        "kind": "lesson",
        "source": {
          "lessonId": "a2-07",
          "grammarFocus": "czasowniki modalne + bezokolicznik: morati, moći, smjeti, trebati; Mogu li…? jako prośba o pozwolenie; ne moraš ≠ ne smiješ",
          "communicativeGoal": "Powiedzieć, co musisz i co możesz, i poprosić o pozwolenie.",
          "sources": [
            "https://www.coe.int/en/web/common-European-framework-reference-languages/table-1-cefr-3.3-common-reference-levels-global-scale",
            "https://www.coe.int/en/web/common-european-framework-reference-languages/cefr-descriptors-search",
            "https://croaticum.ffzg.unizg.hr/?page_id=1106"
          ]
        }
      },
      {
        "id": "a2-02-03",
        "moduleId": "a2-02",
        "order": 3,
        "title": "Jeśli będzie ładnie…",
        "shortDescription": "Powiedzieć, co zrobisz, jeśli coś się wydarzy.",
        "estimatedMinutes": 22,
        "status": "not_started",
        "hasContent": true,
        "kind": "lesson",
        "source": {
          "lessonId": "a2-08",
          "grammarFocus": "zdania warunkowe z ako: ako + czas teraźniejszy, ako bude + przysłówek (ako bude sunčano); inače",
          "communicativeGoal": "Powiedzieć, co zrobisz, jeśli coś się wydarzy.",
          "sources": [
            "https://www.coe.int/en/web/common-European-framework-reference-languages/table-1-cefr-3.3-common-reference-levels-global-scale",
            "https://www.coe.int/en/web/common-european-framework-reference-languages/cefr-descriptors-search",
            "https://croaticum.ffzg.unizg.hr/?page_id=1106"
          ]
        }
      },
      {
        "id": "a2-02-04",
        "moduleId": "a2-02",
        "order": 4,
        "title": "Umawiamy się",
        "shortDescription": "Zaprosić kogoś, przyjąć albo grzecznie odmówić i ustalić termin.",
        "estimatedMinutes": 23,
        "status": "not_started",
        "hasContent": true,
        "kind": "lesson",
        "source": {
          "lessonId": "a2-09",
          "grammarFocus": "zaproszenie, zgoda i odmowa: Imaš li vremena…?, Hoćeš li doći…?, Može li u…?; krótkie zaimki te / ti po ću: Nazvat ću te, Javit ću ti se",
          "communicativeGoal": "Zaprosić kogoś, przyjąć albo grzecznie odmówić i ustalić termin.",
          "sources": [
            "https://www.coe.int/en/web/common-European-framework-reference-languages/table-1-cefr-3.3-common-reference-levels-global-scale",
            "https://www.coe.int/en/web/common-european-framework-reference-languages/cefr-descriptors-search",
            "https://croaticum.ffzg.unizg.hr/?page_id=1106"
          ]
        }
      },
      {
        "id": "a2-02-05",
        "moduleId": "a2-02",
        "order": 5,
        "title": "Powtórka: plany i obowiązki",
        "shortDescription": "Zaplanować tydzień i umówić się: co musisz, co zrobisz i co, jeśli…",
        "estimatedMinutes": 17,
        "status": "not_started",
        "hasContent": true,
        "kind": "review",
        "source": {
          "lessonId": "a2-10",
          "grammarFocus": "utrwalenie futuru, czasowników modalnych, zdań z ako i umawiania się",
          "communicativeGoal": "Zaplanować tydzień i umówić się: co musisz, co zrobisz i co, jeśli…",
          "sources": [
            "https://www.coe.int/en/web/common-European-framework-reference-languages/table-1-cefr-3.3-common-reference-levels-global-scale",
            "https://www.coe.int/en/web/common-european-framework-reference-languages/cefr-descriptors-search",
            "https://croaticum.ffzg.unizg.hr/?page_id=1106"
          ]
        }
      }
    ]
  }
];
