// AUTO-GENERATED by scripts/generate-a1-curriculum.mjs — nie edytuj ręcznie.
// a1-02-04 · Co masz?
// Źródło: curriculum/hr-a1/lexodromia_hr_A1_curriculum.csv (sha256 75adf749ae368f10…) + didactics.json
import type { GeneratedLesson } from "../../../types";

export const LESSON: GeneratedLesson = {
  content: {
    "lessonId": "a1-02-04",
    "vocabulary": [
      {
        "target": "imati",
        "source": "mieć",
        "lemma": "imati",
        "partOfSpeech": "verb",
        "recordId": "A1-0146"
      },
      {
        "target": "nemati",
        "source": "nie mieć",
        "lemma": "nemati",
        "partOfSpeech": "verb",
        "recordId": "A1-0147"
      },
      {
        "target": "auto",
        "source": "samochód",
        "lemma": "auto",
        "partOfSpeech": "noun",
        "recordId": "A1-0148"
      },
      {
        "target": "bicikl",
        "source": "rower",
        "lemma": "bicikl",
        "partOfSpeech": "noun",
        "recordId": "A1-0149"
      },
      {
        "target": "telefon",
        "source": "telefon",
        "lemma": "telefon",
        "partOfSpeech": "noun",
        "recordId": "A1-0150"
      },
      {
        "target": "knjiga",
        "source": "książka",
        "lemma": "knjiga",
        "partOfSpeech": "noun",
        "recordId": "A1-0151"
      },
      {
        "target": "pas",
        "source": "pies",
        "lemma": "pas",
        "partOfSpeech": "noun",
        "recordId": "A1-0152"
      },
      {
        "target": "mačka",
        "source": "kot",
        "lemma": "mačka",
        "partOfSpeech": "noun",
        "recordId": "A1-0153"
      }
    ],
    "steps": [
      {
        "id": "intro",
        "stage": "intro",
        "type": "intro",
        "title": "Co masz?",
        "body": "Po tej lekcji będziesz umieć powiedzieć, co posiadasz i czego nie masz.",
        "goalsTitle": "Powiesz między innymi",
        "goals": [
          "Imam auto. — Mam samochód.",
          "Nemam bicikl. — Nie mam roweru.",
          "Imam novu knjigu. — Mam nową książkę."
        ]
      },
      {
        "id": "word-1",
        "stage": "words",
        "type": "word",
        "target": "imati",
        "source": "mieć",
        "partOfSpeech": "czasownik",
        "example": {
          "target": "Imam auto.",
          "source": "Mam samochód."
        }
      },
      {
        "id": "word-2",
        "stage": "words",
        "type": "word",
        "target": "nemati",
        "source": "nie mieć",
        "partOfSpeech": "czasownik",
        "example": {
          "target": "Nemam bicikl.",
          "source": "Nie mam roweru."
        }
      },
      {
        "id": "word-3",
        "stage": "words",
        "type": "word",
        "target": "auto",
        "source": "samochód",
        "partOfSpeech": "rzeczownik",
        "example": {
          "target": "Imam auto.",
          "source": "Mam samochód."
        }
      },
      {
        "id": "check-1",
        "stage": "words",
        "type": "choice",
        "instruction": "Co znaczy to słowo?",
        "prompt": "imati",
        "options": [
          "mieć",
          "pies",
          "kot"
        ],
        "correctIndex": 0
      },
      {
        "id": "word-4",
        "stage": "words",
        "type": "word",
        "target": "bicikl",
        "source": "rower",
        "partOfSpeech": "rzeczownik",
        "example": {
          "target": "Nemam bicikl.",
          "source": "Nie mam roweru."
        }
      },
      {
        "id": "word-5",
        "stage": "words",
        "type": "word",
        "target": "telefon",
        "source": "telefon",
        "partOfSpeech": "rzeczownik",
        "example": {
          "target": "Imaš li telefon?",
          "source": "Czy masz telefon?"
        }
      },
      {
        "id": "word-6",
        "stage": "words",
        "type": "word",
        "target": "knjiga",
        "source": "książka",
        "partOfSpeech": "rzeczownik",
        "example": {
          "target": "Imam novu knjigu.",
          "source": "Mam nową książkę."
        }
      },
      {
        "id": "check-2",
        "stage": "words",
        "type": "choice",
        "instruction": "Jak powiesz to po chorwacku?",
        "prompt": "telefon",
        "options": [
          "pas",
          "telefon",
          "imati"
        ],
        "correctIndex": 1
      },
      {
        "id": "word-7",
        "stage": "words",
        "type": "word",
        "target": "pas",
        "source": "pies",
        "partOfSpeech": "rzeczownik"
      },
      {
        "id": "word-8",
        "stage": "words",
        "type": "word",
        "target": "mačka",
        "source": "kot",
        "partOfSpeech": "rzeczownik",
        "example": {
          "target": "On nema mačku.",
          "source": "On nie ma kota."
        }
      },
      {
        "id": "check-3",
        "stage": "words",
        "type": "choice",
        "instruction": "Co znaczy to słowo?",
        "prompt": "mačka",
        "options": [
          "pies",
          "nie mieć",
          "kot"
        ],
        "correctIndex": 2
      },
      {
        "id": "structure",
        "stage": "structure",
        "type": "structure",
        "title": "Imam / nemam",
        "explanation": "Imati to „mieć”, a nemati — „nie mieć” (jedno słowo!). Rzeczowniki żeńskie po imam zmieniają -a na -u: knjiga → Imam knjigu, mačka → On nema mačku. Po nemati usłyszysz też formę jak w polskim „nie mam kota”: nema mačke — obie są poprawne.",
        "examples": [
          {
            "target": "Imam auto.",
            "source": "Mam samochód."
          },
          {
            "target": "Nemam bicikl.",
            "source": "Nie mam roweru."
          },
          {
            "target": "Imam novu knjigu.",
            "source": "Mam nową książkę."
          }
        ],
        "note": "Pas → psa: Ona ima psa — jak po polsku „ma psa”."
      },
      {
        "id": "gap",
        "stage": "structure",
        "type": "gap",
        "instruction": "Uzupełnij lukę.",
        "before": "Imam novu",
        "after": ".",
        "accepted": [
          "knjigu"
        ],
        "translation": "Mam nową książkę."
      },
      {
        "id": "comprehend",
        "stage": "practice",
        "type": "choice",
        "instruction": "Co znaczy to zdanie?",
        "prompt": "On nema mačku.",
        "options": [
          "On nie ma kota.",
          "Mam samochód.",
          "Nie mam roweru."
        ],
        "correctIndex": 0
      },
      {
        "id": "translate-1",
        "stage": "practice",
        "type": "translate",
        "instruction": "Przetłumacz na chorwacki.",
        "prompt": "Mam samochód.",
        "accepted": [
          "Imam auto.",
          "Ja imam auto."
        ]
      },
      {
        "id": "order",
        "stage": "practice",
        "type": "order",
        "instruction": "Ułóż zdanie.",
        "translation": "Czy masz telefon?",
        "tokens": [
          "imaš",
          "telefon",
          "li"
        ],
        "accepted": [
          "Imaš li telefon?"
        ]
      },
      {
        "id": "translate-2",
        "stage": "practice",
        "type": "translate",
        "instruction": "Przetłumacz na chorwacki.",
        "prompt": "Nie mam roweru.",
        "accepted": [
          "Nemam bicikl.",
          "Nemam bicikla.",
          "Ja nemam bicikl.",
          "Ja nemam bicikla."
        ]
      },
      {
        "id": "dialog",
        "stage": "dialog",
        "type": "dialog",
        "title": "Co masz?",
        "turns": [
          {
            "kind": "line",
            "line": {
              "speaker": "Marko",
              "text": "Imaš li telefon?",
              "translation": "Czy masz telefon?"
            }
          },
          {
            "kind": "reply",
            "prompt": "Odpowiedz, że masz.",
            "accepted": [
              "Da, imam telefon.",
              "Imam telefon."
            ],
            "pattern": "^(da )?imam( telefon)?$",
            "suggestion": "Da, imam telefon."
          },
          {
            "kind": "line",
            "line": {
              "speaker": "Marko",
              "text": "Imaš li psa?",
              "translation": "Masz psa?"
            }
          },
          {
            "kind": "reply",
            "prompt": "Powiedz, że nie masz psa, ale masz kota.",
            "accepted": [
              "Nemam psa, ali imam mačku."
            ],
            "pattern": "^(ne )?nemam psa (ali )?imam mačku$",
            "suggestion": "Nemam psa, ali imam mačku."
          }
        ]
      },
      {
        "id": "free",
        "stage": "dialog",
        "type": "free",
        "instruction": "Napisz, co masz, a czego nie masz.",
        "points": [
          "co masz",
          "czego nie masz"
        ],
        "keywords": [
          {
            "any": [
              "imam"
            ],
            "label": "imam …"
          },
          {
            "any": [
              "nemam"
            ],
            "label": "nemam …"
          }
        ],
        "minSentences": 2,
        "sample": "Imam auto i psa. Nemam bicikl."
      },
      {
        "id": "summary",
        "stage": "summary",
        "type": "summary",
        "title": "Lekcja ukończona",
        "recap": [
          "Imam auto. — Mam samochód.",
          "Nemam bicikl. — Nie mam roweru.",
          "Imam novu knjigu. — Mam nową książkę.",
          "Ona ima psa. — Ona ma psa."
        ]
      }
    ]
  },
  material: {
    "sourceLessonId": "a1-09",
    "grammarFocus": "imati/nemati; biernik najczęstszych rzeczowników",
    "communicativeGoal": "Powiedzieć, co posiadasz i czego nie masz.",
    "sources": [
      "https://www.coe.int/en/web/common-European-framework-reference-languages/table-1-cefr-3.3-common-reference-levels-global-scale",
      "https://www.coe.int/en/web/common-european-framework-reference-languages/cefr-descriptors-search",
      "https://croaticum.ffzg.unizg.hr/?page_id=1106",
      "https://a1.ffzg.unizg.hr/",
      "https://www.easy-croatian.com/2014/11/3.html",
      "https://www.easy-croatian.com/2014/11/a4.html"
    ],
    "records": [
      {
        "recordId": "A1-0145",
        "type": "lesson",
        "sequence": 0,
        "hr": "",
        "pl": "",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "",
        "acceptedAnswers": [],
        "notes": "Projekt autorski oparty na deskryptorach CEFR A1 oraz zakresie początkujących kursów Croaticum. Treści nie są kopią podręcznika.",
        "tags": [
          "curriculum",
          "cefr-a1",
          "croatian"
        ]
      },
      {
        "recordId": "A1-0146",
        "type": "vocabulary",
        "sequence": 1,
        "hr": "imati",
        "pl": "mieć",
        "lemma": "imati",
        "partOfSpeech": "verb",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "imati"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A1-0147",
        "type": "vocabulary",
        "sequence": 2,
        "hr": "nemati",
        "pl": "nie mieć",
        "lemma": "nemati",
        "partOfSpeech": "verb",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "nemati"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A1-0148",
        "type": "vocabulary",
        "sequence": 3,
        "hr": "auto",
        "pl": "samochód",
        "lemma": "auto",
        "partOfSpeech": "noun",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "auto"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A1-0149",
        "type": "vocabulary",
        "sequence": 4,
        "hr": "bicikl",
        "pl": "rower",
        "lemma": "bicikl",
        "partOfSpeech": "noun",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "bicikl"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A1-0150",
        "type": "vocabulary",
        "sequence": 5,
        "hr": "telefon",
        "pl": "telefon",
        "lemma": "telefon",
        "partOfSpeech": "noun",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "telefon"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A1-0151",
        "type": "vocabulary",
        "sequence": 6,
        "hr": "knjiga",
        "pl": "książka",
        "lemma": "knjiga",
        "partOfSpeech": "noun",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "knjiga"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A1-0152",
        "type": "vocabulary",
        "sequence": 7,
        "hr": "pas",
        "pl": "pies",
        "lemma": "pas",
        "partOfSpeech": "noun",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "pas"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A1-0153",
        "type": "vocabulary",
        "sequence": 8,
        "hr": "mačka",
        "pl": "kot",
        "lemma": "mačka",
        "partOfSpeech": "noun",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "mačka"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A1-0154",
        "type": "sentence",
        "sequence": 1,
        "hr": "Imam auto.",
        "pl": "Mam samochód.",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "Imam auto."
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych warto akceptować brak części znaków diakrytycznych jako soft error, ale pokazać poprawną pisownię.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A1-0155",
        "type": "sentence",
        "sequence": 2,
        "hr": "Nemam bicikl.",
        "pl": "Nie mam roweru.",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "Nemam bicikl."
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych warto akceptować brak części znaków diakrytycznych jako soft error, ale pokazać poprawną pisownię.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A1-0156",
        "type": "sentence",
        "sequence": 3,
        "hr": "Imam novu knjigu.",
        "pl": "Mam nową książkę.",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "Imam novu knjigu."
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych warto akceptować brak części znaków diakrytycznych jako soft error, ale pokazać poprawną pisownię.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A1-0157",
        "type": "sentence",
        "sequence": 4,
        "hr": "Ona ima psa.",
        "pl": "Ona ma psa.",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "Ona ima psa."
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych warto akceptować brak części znaków diakrytycznych jako soft error, ale pokazać poprawną pisownię.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A1-0158",
        "type": "sentence",
        "sequence": 5,
        "hr": "On nema mačku.",
        "pl": "On nie ma kota.",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "On nema mačku."
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych warto akceptować brak części znaków diakrytycznych jako soft error, ale pokazać poprawną pisownię.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A1-0159",
        "type": "sentence",
        "sequence": 6,
        "hr": "Imaš li telefon?",
        "pl": "Czy masz telefon?",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "Imaš li telefon?"
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych warto akceptować brak części znaków diakrytycznych jako soft error, ale pokazać poprawną pisownię.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A1-0160",
        "type": "exercise_blueprint",
        "sequence": 1,
        "hr": "",
        "pl": "",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "multiple_choice",
        "acceptedAnswers": [],
        "notes": "Wybierz poprawne znaczenie lub odpowiedź do krótkiego promptu.",
        "tags": [
          "exercise",
          "lesson-player"
        ]
      },
      {
        "recordId": "A1-0161",
        "type": "exercise_blueprint",
        "sequence": 2,
        "hr": "",
        "pl": "",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation",
        "acceptedAnswers": [],
        "notes": "Przetłumacz 1 krótkie zdanie PL→HR, akceptując poprawne warianty.",
        "tags": [
          "exercise",
          "lesson-player"
        ]
      },
      {
        "recordId": "A1-0162",
        "type": "exercise_blueprint",
        "sequence": 3,
        "hr": "",
        "pl": "",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "free_response",
        "acceptedAnswers": [],
        "notes": "Napisz 1–2 własne zdania z materiałem lekcji; oceń sens i kluczową konstrukcję.",
        "tags": [
          "exercise",
          "lesson-player"
        ]
      }
    ]
  },
};
