// AUTO-GENERATED by scripts/generate-a1-curriculum.mjs — nie edytuj ręcznie.
// a1-08-02 · Co zrobię jutro?
// Źródło: curriculum/hr-a1/lexodromia_hr_A1_curriculum.csv (sha256 75adf749ae368f10…) + didactics.json
import type { GeneratedLesson } from "../../../types";

export const LESSON: GeneratedLesson = {
  content: {
    "lessonId": "a1-08-02",
    "vocabulary": [
      {
        "target": "sutra",
        "source": "jutro",
        "lemma": "sutra",
        "partOfSpeech": "adverb",
        "recordId": "A1-0650"
      },
      {
        "target": "ću",
        "source": "będę / partykuła futurum 1 os.",
        "lemma": "ću",
        "partOfSpeech": "auxiliary",
        "recordId": "A1-0651"
      },
      {
        "target": "ćeš",
        "source": "będziesz / partykuła futurum 2 os.",
        "lemma": "ćeš",
        "partOfSpeech": "auxiliary",
        "recordId": "A1-0652"
      },
      {
        "target": "raditi",
        "source": "pracować",
        "lemma": "raditi",
        "partOfSpeech": "verb",
        "recordId": "A1-0653"
      },
      {
        "target": "ići",
        "source": "iść / jechać",
        "lemma": "ići",
        "partOfSpeech": "verb",
        "recordId": "A1-0654"
      },
      {
        "target": "učiti",
        "source": "uczyć się",
        "lemma": "učiti",
        "partOfSpeech": "verb",
        "recordId": "A1-0655"
      },
      {
        "target": "odmoriti se",
        "source": "odpocząć",
        "lemma": "odmoriti se",
        "partOfSpeech": "verb",
        "recordId": "A1-0656"
      },
      {
        "target": "kasnije",
        "source": "później",
        "lemma": "kasnije",
        "partOfSpeech": "adverb",
        "recordId": "A1-0657"
      }
    ],
    "steps": [
      {
        "id": "intro",
        "stage": "intro",
        "type": "intro",
        "title": "Co zrobię jutro?",
        "body": "Po tej lekcji będziesz umieć powiedzieć 2–3 proste rzeczy o jutrze.",
        "goalsTitle": "Powiesz między innymi",
        "goals": [
          {
            "target": "Sutra ću raditi.",
            "source": "Jutro będę pracować."
          },
          {
            "target": "Sutra ću učiti hrvatski.",
            "source": "Jutro będę uczyć się chorwackiego."
          },
          {
            "target": "Kasnije ću se odmoriti.",
            "source": "Później odpocznę."
          }
        ]
      },
      {
        "id": "word-1",
        "stage": "words",
        "type": "word",
        "target": "sutra",
        "source": "jutro",
        "partOfSpeech": "przysłówek",
        "example": {
          "target": "Sutra ću raditi.",
          "source": "Jutro będę pracować."
        }
      },
      {
        "id": "word-2",
        "stage": "words",
        "type": "word",
        "target": "ću",
        "source": "będę / partykuła futurum 1 os.",
        "partOfSpeech": "forma pomocnicza",
        "example": {
          "target": "Sutra ću raditi.",
          "source": "Jutro będę pracować."
        }
      },
      {
        "id": "word-3",
        "stage": "words",
        "type": "word",
        "target": "ćeš",
        "source": "będziesz / partykuła futurum 2 os.",
        "partOfSpeech": "forma pomocnicza"
      },
      {
        "id": "check-1",
        "stage": "words",
        "type": "choice",
        "instruction": "Co znaczy to słowo?",
        "prompt": "ću",
        "options": [
          "będziesz / partykuła futurum 2 os.",
          "będę / partykuła futurum 1 os.",
          "iść / jechać"
        ],
        "correctIndex": 1,
        "targetText": "prompt"
      },
      {
        "id": "word-4",
        "stage": "words",
        "type": "word",
        "target": "raditi",
        "source": "pracować",
        "partOfSpeech": "czasownik",
        "example": {
          "target": "Sutra ću raditi.",
          "source": "Jutro będę pracować."
        }
      },
      {
        "id": "word-5",
        "stage": "words",
        "type": "word",
        "target": "ići",
        "source": "iść / jechać",
        "partOfSpeech": "czasownik",
        "example": {
          "target": "Hoćeš li ići sa mnom?",
          "source": "Czy pójdziesz / pojedziesz ze mną?"
        }
      },
      {
        "id": "word-6",
        "stage": "words",
        "type": "word",
        "target": "učiti",
        "source": "uczyć się",
        "partOfSpeech": "czasownik",
        "example": {
          "target": "Sutra ću učiti hrvatski.",
          "source": "Jutro będę uczyć się chorwackiego."
        }
      },
      {
        "id": "check-2",
        "stage": "words",
        "type": "choice",
        "instruction": "Jak powiesz to po chorwacku?",
        "prompt": "uczyć się",
        "options": [
          "ću",
          "ići",
          "učiti"
        ],
        "correctIndex": 2,
        "targetText": "options"
      },
      {
        "id": "word-7",
        "stage": "words",
        "type": "word",
        "target": "odmoriti se",
        "source": "odpocząć",
        "partOfSpeech": "czasownik"
      },
      {
        "id": "word-8",
        "stage": "words",
        "type": "word",
        "target": "kasnije",
        "source": "później",
        "partOfSpeech": "przysłówek",
        "example": {
          "target": "Kasnije ću se odmoriti.",
          "source": "Później odpocznę."
        }
      },
      {
        "id": "check-3",
        "stage": "words",
        "type": "choice",
        "instruction": "Co znaczy to słowo?",
        "prompt": "kasnije",
        "options": [
          "później",
          "uczyć się",
          "odpocząć"
        ],
        "correctIndex": 0,
        "targetText": "prompt"
      },
      {
        "id": "structure",
        "stage": "structure",
        "type": "structure",
        "title": "Sutra ću raditi",
        "explanation": "O przyszłości mówisz ću (ja) albo ćeš (ty) + bezokolicznik: Sutra ću raditi — jutro będę pracować. Ću nie otwiera zdania: Sutra ću učiti, Kasnije ću se odmoriti. Pytanie zaczynasz od Hoćeš li…? — Hoćeš li ići sa mnom?",
        "examples": [
          {
            "target": "Sutra ću raditi.",
            "source": "Jutro będę pracować."
          },
          {
            "target": "Sutra ću učiti hrvatski.",
            "source": "Jutro będę uczyć się chorwackiego."
          },
          {
            "target": "Kasnije ću se odmoriti.",
            "source": "Później odpocznę."
          },
          {
            "target": "Hoćeš li ići sa mnom?",
            "source": "Czy pójdziesz / pojedziesz ze mną?"
          }
        ],
        "note": "My: ćemo — U subotu ćemo ići na more."
      },
      {
        "id": "gap",
        "stage": "structure",
        "type": "gap",
        "instruction": "Uzupełnij lukę.",
        "before": "Sutra",
        "after": "učiti hrvatski.",
        "accepted": [
          "ću"
        ],
        "translation": "Jutro będę uczyć się chorwackiego."
      },
      {
        "id": "comprehend",
        "stage": "practice",
        "type": "choice",
        "instruction": "Co znaczy to zdanie?",
        "prompt": "Hoćeš li ići sa mnom?",
        "options": [
          "Jutro będę pracować.",
          "Czy pójdziesz / pojedziesz ze mną?",
          "Jutro będę uczyć się chorwackiego."
        ],
        "correctIndex": 1,
        "targetText": "prompt"
      },
      {
        "id": "choice-1",
        "stage": "practice",
        "type": "choice",
        "instruction": "Wybierz zdanie o jutrze.",
        "prompt": "Jutro będę się uczyć chorwackiego.",
        "options": [
          "Jučer sam učio hrvatski.",
          "Sutra ću učiti hrvatski.",
          "Sutra učim hrvatski."
        ],
        "correctIndex": 1,
        "explanation": "Przyszłość: ću + bezokolicznik (učiti).",
        "targetText": "options"
      },
      {
        "id": "translate-1",
        "stage": "practice",
        "type": "translate",
        "instruction": "Przetłumacz na chorwacki.",
        "prompt": "Jutro będę pracować.",
        "accepted": [
          "Sutra ću raditi.",
          "Radit ću sutra."
        ]
      },
      {
        "id": "order",
        "stage": "practice",
        "type": "order",
        "instruction": "Ułóż zdanie.",
        "translation": "Później odpocznę.",
        "tokens": [
          "ću",
          "odmoriti",
          "kasnije",
          "se"
        ],
        "accepted": [
          "Kasnije ću se odmoriti."
        ]
      },
      {
        "id": "translate-2",
        "stage": "practice",
        "type": "translate",
        "instruction": "Przetłumacz na chorwacki.",
        "prompt": "Wieczorem będę oglądać film.",
        "accepted": [
          "Navečer ću gledati film.",
          "Gledat ću film navečer."
        ]
      },
      {
        "id": "dialog",
        "stage": "dialog",
        "type": "dialog",
        "title": "Plany na jutro",
        "turns": [
          {
            "kind": "line",
            "line": {
              "speaker": "Marko",
              "text": "Što ćeš raditi sutra?",
              "translation": "Co będziesz robić jutro?"
            }
          },
          {
            "kind": "reply",
            "prompt": "Powiedz, co będziesz robić jutro.",
            "accepted": [
              "Sutra ću raditi.",
              "Sutra ću učiti hrvatski."
            ],
            "pattern": "^sutra ću (raditi|učiti hrvatski|ići u grad|ići na more|gledati film|se odmoriti)$",
            "suggestion": "Sutra ću raditi."
          },
          {
            "kind": "line",
            "line": {
              "speaker": "Marko",
              "text": "Hoćeš li ići sa mnom?",
              "translation": "Czy pójdziesz / pojedziesz ze mną?"
            }
          },
          {
            "kind": "reply",
            "prompt": "Odpowiedz na zaproszenie.",
            "accepted": [
              "Hoću!",
              "Može!",
              "Ne mogu."
            ],
            "pattern": "^(da )?(hoću|može|ne mogu|naravno)( rado)?$",
            "suggestion": "Hoću!"
          }
        ]
      },
      {
        "id": "free",
        "stage": "dialog",
        "type": "free",
        "instruction": "Napisz 2 zdania o tym, co zrobisz jutro.",
        "points": [
          "co zrobisz",
          "kiedy"
        ],
        "keywords": [
          {
            "any": [
              "ću"
            ],
            "label": "ću + bezokolicznik"
          },
          {
            "any": [
              "sutra",
              "kasnije",
              "navečer"
            ],
            "label": "kiedy"
          }
        ],
        "minSentences": 2,
        "sample": "Sutra ću raditi. Navečer ću gledati film."
      },
      {
        "id": "summary",
        "stage": "summary",
        "type": "summary",
        "title": "Lekcja ukończona",
        "recap": [
          {
            "target": "Sutra ću raditi.",
            "source": "Jutro będę pracować."
          },
          {
            "target": "Sutra ću učiti hrvatski.",
            "source": "Jutro będę uczyć się chorwackiego."
          },
          {
            "target": "Kasnije ću se odmoriti.",
            "source": "Później odpocznę."
          },
          {
            "target": "Hoćeš li ići sa mnom?",
            "source": "Czy pójdziesz / pojedziesz ze mną?"
          }
        ]
      }
    ]
  },
  material: {
    "sourceLessonId": "a1-37",
    "grammarFocus": "futur I jako wprowadzenie: ću/ćeš + bezokolicznik",
    "communicativeGoal": "Powiedzieć 2–3 proste rzeczy o jutrze.",
    "sources": [
      "https://www.coe.int/en/web/common-European-framework-reference-languages/table-1-cefr-3.3-common-reference-levels-global-scale",
      "https://www.coe.int/en/web/common-european-framework-reference-languages/cefr-descriptors-search",
      "https://croaticum.ffzg.unizg.hr/?page_id=1106",
      "https://a1.ffzg.unizg.hr/",
      "https://www.easy-croatian.com/2014/11/40.html"
    ],
    "records": [
      {
        "recordId": "A1-0649",
        "type": "lesson",
        "sequence": 0,
        "hr": "",
        "pl": "",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "",
        "acceptedAnswers": [],
        "notes": "Projekt autorski oparty na deskryptorach CEFR A1 oraz zakresie początkujących kursów Croaticum. Treści nie są kopią podręcznika.",
        "tags": [
          "curriculum",
          "cefr-a1",
          "croatian"
        ]
      },
      {
        "recordId": "A1-0650",
        "type": "vocabulary",
        "sequence": 1,
        "hr": "sutra",
        "pl": "jutro",
        "lemma": "sutra",
        "partOfSpeech": "adverb",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "sutra"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A1-0651",
        "type": "vocabulary",
        "sequence": 2,
        "hr": "ću",
        "pl": "będę / partykuła futurum 1 os.",
        "lemma": "ću",
        "partOfSpeech": "auxiliary",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "ću"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A1-0652",
        "type": "vocabulary",
        "sequence": 3,
        "hr": "ćeš",
        "pl": "będziesz / partykuła futurum 2 os.",
        "lemma": "ćeš",
        "partOfSpeech": "auxiliary",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "ćeš"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A1-0653",
        "type": "vocabulary",
        "sequence": 4,
        "hr": "raditi",
        "pl": "pracować",
        "lemma": "raditi",
        "partOfSpeech": "verb",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "raditi"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A1-0654",
        "type": "vocabulary",
        "sequence": 5,
        "hr": "ići",
        "pl": "iść / jechać",
        "lemma": "ići",
        "partOfSpeech": "verb",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "ići"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A1-0655",
        "type": "vocabulary",
        "sequence": 6,
        "hr": "učiti",
        "pl": "uczyć się",
        "lemma": "učiti",
        "partOfSpeech": "verb",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "učiti"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A1-0656",
        "type": "vocabulary",
        "sequence": 7,
        "hr": "odmoriti se",
        "pl": "odpocząć",
        "lemma": "odmoriti se",
        "partOfSpeech": "verb",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "odmoriti se"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A1-0657",
        "type": "vocabulary",
        "sequence": 8,
        "hr": "kasnije",
        "pl": "później",
        "lemma": "kasnije",
        "partOfSpeech": "adverb",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "kasnije"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A1-0658",
        "type": "sentence",
        "sequence": 1,
        "hr": "Sutra ću raditi.",
        "pl": "Jutro będę pracować.",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "Sutra ću raditi."
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych warto akceptować brak części znaków diakrytycznych jako soft error, ale pokazać poprawną pisownię.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A1-0659",
        "type": "sentence",
        "sequence": 2,
        "hr": "Sutra ću učiti hrvatski.",
        "pl": "Jutro będę uczyć się chorwackiego.",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "Sutra ću učiti hrvatski."
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych warto akceptować brak części znaków diakrytycznych jako soft error, ale pokazać poprawną pisownię.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A1-0660",
        "type": "sentence",
        "sequence": 3,
        "hr": "Kasnije ću se odmoriti.",
        "pl": "Później odpocznę.",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "Kasnije ću se odmoriti."
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych warto akceptować brak części znaków diakrytycznych jako soft error, ale pokazać poprawną pisownię.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A1-0661",
        "type": "sentence",
        "sequence": 4,
        "hr": "Hoćeš li ići sa mnom?",
        "pl": "Czy pójdziesz / pojedziesz ze mną?",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "Hoćeš li ići sa mnom?"
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych warto akceptować brak części znaków diakrytycznych jako soft error, ale pokazać poprawną pisownię.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A1-0662",
        "type": "sentence",
        "sequence": 5,
        "hr": "U subotu ćemo ići na more.",
        "pl": "W sobotę pojedziemy nad morze.",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "U subotu ćemo ići na more."
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych warto akceptować brak części znaków diakrytycznych jako soft error, ale pokazać poprawną pisownię.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A1-0663",
        "type": "sentence",
        "sequence": 6,
        "hr": "Navečer ću gledati film.",
        "pl": "Wieczorem będę oglądać film.",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "Navečer ću gledati film."
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych warto akceptować brak części znaków diakrytycznych jako soft error, ale pokazać poprawną pisownię.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A1-0664",
        "type": "exercise_blueprint",
        "sequence": 1,
        "hr": "",
        "pl": "",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "multiple_choice",
        "acceptedAnswers": [],
        "notes": "Wybierz poprawne znaczenie lub odpowiedź do krótkiego promptu.",
        "tags": [
          "exercise",
          "lesson-player"
        ]
      },
      {
        "recordId": "A1-0665",
        "type": "exercise_blueprint",
        "sequence": 2,
        "hr": "",
        "pl": "",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation",
        "acceptedAnswers": [],
        "notes": "Przetłumacz 1 krótkie zdanie PL→HR, akceptując poprawne warianty.",
        "tags": [
          "exercise",
          "lesson-player"
        ]
      },
      {
        "recordId": "A1-0666",
        "type": "exercise_blueprint",
        "sequence": 3,
        "hr": "",
        "pl": "",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "free_response",
        "acceptedAnswers": [],
        "notes": "Napisz 1–2 własne zdania z materiałem lekcji; oceń sens i kluczową konstrukcję.",
        "tags": [
          "exercise",
          "lesson-player"
        ]
      }
    ]
  },
};
