// AUTO-GENERATED by scripts/generate-a1-curriculum.mjs — nie edytuj ręcznie.
// a1-08-05 · Test A1
// Źródło: curriculum/hr-a1/lexodromia_hr_A1_curriculum.csv (sha256 ba0474dcbdcbe04e…) + didactics.json
import type { GeneratedLesson } from "../../../types";

export const LESSON: GeneratedLesson = {
  content: {
    "lessonId": "a1-08-05",
    "mode": "test",
    "vocabulary": [
      {
        "target": "test",
        "source": "test",
        "lemma": "test",
        "partOfSpeech": "noun",
        "recordId": "A1-0704"
      },
      {
        "target": "zadatak",
        "source": "zadanie",
        "lemma": "zadatak",
        "partOfSpeech": "noun",
        "recordId": "A1-0705"
      },
      {
        "target": "točno",
        "source": "poprawnie",
        "lemma": "točno",
        "partOfSpeech": "adverb",
        "recordId": "A1-0706"
      },
      {
        "target": "netočno",
        "source": "niepoprawnie",
        "lemma": "netočno",
        "partOfSpeech": "adverb",
        "recordId": "A1-0707"
      },
      {
        "target": "odabrati",
        "source": "wybrać",
        "lemma": "odabrati",
        "partOfSpeech": "verb",
        "recordId": "A1-0708"
      },
      {
        "target": "napisati",
        "source": "napisać",
        "lemma": "napisati",
        "partOfSpeech": "verb",
        "recordId": "A1-0709"
      },
      {
        "target": "poslušati",
        "source": "posłuchać",
        "lemma": "poslušati",
        "partOfSpeech": "verb",
        "recordId": "A1-0710"
      },
      {
        "target": "završiti",
        "source": "zakończyć",
        "lemma": "završiti",
        "partOfSpeech": "verb",
        "recordId": "A1-0711"
      }
    ],
    "steps": [
      {
        "id": "intro",
        "stage": "intro",
        "type": "intro",
        "title": "Test A1",
        "body": "Test obejmuje materiał całego poziomu A1. Nie ma tu zaliczenia ani oblania — na końcu zobaczysz, co masz dobrze opanowane, a co warto powtórzyć.",
        "goalsTitle": "Sześć krótkich części",
        "goals": [
          "słownictwo",
          "czytanie",
          "słuchanie",
          "gramatyka w kontekście",
          "tłumaczenie",
          "krótka wypowiedź"
        ]
      },
      {
        "id": "instructions",
        "stage": "intro",
        "type": "vocabList",
        "title": "Słowa z poleceń testu",
        "note": "Polecenia w teście są po chorwacku — pod spodem zawsze zobaczysz tłumaczenie.",
        "items": [
          {
            "target": "test",
            "source": "test",
            "partOfSpeech": "rzeczownik"
          },
          {
            "target": "zadatak",
            "source": "zadanie",
            "partOfSpeech": "rzeczownik"
          },
          {
            "target": "točno",
            "source": "poprawnie",
            "partOfSpeech": "przysłówek"
          },
          {
            "target": "netočno",
            "source": "niepoprawnie",
            "partOfSpeech": "przysłówek"
          },
          {
            "target": "odabrati",
            "source": "wybrać",
            "partOfSpeech": "czasownik"
          },
          {
            "target": "napisati",
            "source": "napisać",
            "partOfSpeech": "czasownik"
          },
          {
            "target": "poslušati",
            "source": "posłuchać",
            "partOfSpeech": "czasownik"
          },
          {
            "target": "završiti",
            "source": "zakończyć",
            "partOfSpeech": "czasownik"
          }
        ]
      },
      {
        "id": "vocab-1",
        "stage": "words",
        "type": "choice",
        "instruction": "Wybierz poprawne znaczenie.",
        "prompt": "hvala",
        "options": [
          "dziękuję",
          "kupić",
          "muzyka"
        ],
        "correctIndex": 0,
        "targetText": "prompt",
        "section": "vocabulary",
        "promptAudioSrc": "/audio/hr/a1/module-01/hvala.mp3"
      },
      {
        "id": "vocab-2",
        "stage": "words",
        "type": "choice",
        "instruction": "Wybierz poprawne znaczenie.",
        "prompt": "obitelj",
        "options": [
          "kot",
          "rodzina",
          "lotnisko"
        ],
        "correctIndex": 1,
        "targetText": "prompt",
        "section": "vocabulary"
      },
      {
        "id": "vocab-3",
        "stage": "words",
        "type": "choice",
        "instruction": "Wybierz poprawne znaczenie.",
        "prompt": "kava",
        "options": [
          "apteka",
          "rozmiar",
          "kawa"
        ],
        "correctIndex": 2,
        "targetText": "prompt",
        "section": "vocabulary"
      },
      {
        "id": "vocab-4",
        "stage": "words",
        "type": "choice",
        "instruction": "Wybierz poprawne znaczenie.",
        "prompt": "trgovina",
        "options": [
          "sklep",
          "pić",
          "spokojny"
        ],
        "correctIndex": 0,
        "targetText": "prompt",
        "section": "vocabulary"
      },
      {
        "id": "vocab-5",
        "stage": "words",
        "type": "choice",
        "instruction": "Wybierz poprawne znaczenie.",
        "prompt": "vlak",
        "options": [
          "pisanie",
          "pociąg",
          "klucz"
        ],
        "correctIndex": 1,
        "targetText": "prompt",
        "section": "vocabulary"
      },
      {
        "id": "vocab-6",
        "stage": "words",
        "type": "choice",
        "instruction": "Wybierz poprawne znaczenie.",
        "prompt": "kiša",
        "options": [
          "Polska",
          "morze",
          "deszcz"
        ],
        "correctIndex": 2,
        "targetText": "prompt",
        "section": "vocabulary"
      },
      {
        "id": "reading",
        "stage": "practice",
        "section": "reading",
        "type": "reading",
        "instructionTarget": {
          "target": "Pročitaj i odaberi točan odgovor.",
          "source": "Przeczytaj i wybierz poprawną odpowiedź."
        },
        "instruction": "Przeczytaj tekst i odpowiedz na pytania.",
        "title": "Marta",
        "text": [
          {
            "target": "Zovem se Marta i iz Poljske sam.",
            "source": ""
          },
          {
            "target": "Živim u Krakovu i radim u uredu.",
            "source": ""
          },
          {
            "target": "Svaki dan učim hrvatski.",
            "source": ""
          },
          {
            "target": "Volim plivati i čitati.",
            "source": ""
          },
          {
            "target": "Jučer sam bila kod kuće.",
            "source": ""
          },
          {
            "target": "U subotu ću ići na more.",
            "source": ""
          }
        ],
        "questions": [
          {
            "prompt": "Skąd jest Marta?",
            "options": [
              "Z Polski",
              "Z Chorwacji",
              "Z Zagrzebia"
            ],
            "correctIndex": 0
          },
          {
            "prompt": "Gdzie pracuje Marta?",
            "options": [
              "W szkole",
              "W biurze",
              "W banku"
            ],
            "correctIndex": 1
          },
          {
            "prompt": "Co Marta zrobi w sobotę?",
            "options": [
              "Będzie pracować",
              "Pójdzie do sklepu",
              "Pojedzie nad morze"
            ],
            "correctIndex": 2
          }
        ]
      },
      {
        "id": "listening",
        "stage": "practice",
        "type": "listening",
        "instruction": "Posłuchaj dialogu i odpowiedz na pytanie.",
        "instructionTarget": {
          "target": "Poslušaj kratki dijalog.",
          "source": "Posłuchaj krótkiego dialogu."
        },
        "title": "Na dworcu kolejowym",
        "lines": [
          {
            "speaker": "Marko",
            "text": "Dobar dan. Jednu kartu za Split, molim.",
            "translation": "Dzień dobry. Poproszę jeden bilet do Splitu.",
            "audio": "/audio/listening/hr-a1/a1-kolodvor/01-marko.mp3"
          },
          {
            "speaker": "Ana",
            "text": "U jednom smjeru ili povratnu?",
            "translation": "W jedną stronę czy powrotny?",
            "audio": "/audio/listening/hr-a1/a1-kolodvor/02-ana.mp3"
          },
          {
            "speaker": "Marko",
            "text": "Povratnu, molim. Kada polazi vlak?",
            "translation": "Powrotny, proszę. Kiedy odjeżdża pociąg?",
            "audio": "/audio/listening/hr-a1/a1-kolodvor/03-marko.mp3"
          },
          {
            "speaker": "Ana",
            "text": "U deset sati i petnaest minuta, s trećeg perona.",
            "translation": "O dziesiątej piętnaście, z trzeciego peronu.",
            "audio": "/audio/listening/hr-a1/a1-kolodvor/04-ana.mp3"
          },
          {
            "speaker": "Marko",
            "text": "Hvala.",
            "translation": "Dziękuję.",
            "audio": "/audio/listening/hr-a1/a1-kolodvor/05-marko.mp3"
          }
        ],
        "questions": [
          {
            "prompt": "Dokąd jedzie Marko?",
            "options": [
              "Do Zadaru",
              "Do Splitu",
              "Do Zagrzebia"
            ],
            "correctIndex": 1
          },
          {
            "prompt": "Jaki bilet kupuje?",
            "options": [
              "Powrotny",
              "W jedną stronę",
              "Dwa bilety"
            ],
            "correctIndex": 0
          },
          {
            "prompt": "Z którego peronu odjeżdża pociąg?",
            "options": [
              "Z trzeciego",
              "Z pierwszego",
              "Z piątego"
            ],
            "correctIndex": 0
          }
        ],
        "section": "listening"
      },
      {
        "id": "grammar-1",
        "stage": "structure",
        "type": "gap",
        "instruction": "Uzupełnij lukę.",
        "before": "",
        "after": "sam kod kuće.",
        "accepted": [
          "Bila"
        ],
        "translation": "Byłam w domu.",
        "section": "grammar",
        "instructionTarget": {
          "target": "Dopuni rečenicu.",
          "source": "Uzupełnij zdanie."
        }
      },
      {
        "id": "grammar-2",
        "stage": "structure",
        "type": "gap",
        "instruction": "Uzupełnij lukę.",
        "before": "Sutra",
        "after": "raditi.",
        "accepted": [
          "ću"
        ],
        "translation": "Jutro będę pracować.",
        "section": "grammar",
        "instructionTarget": {
          "target": "Dopuni rečenicu.",
          "source": "Uzupełnij zdanie."
        }
      },
      {
        "id": "grammar-3",
        "stage": "structure",
        "type": "gap",
        "instruction": "Uzupełnij lukę.",
        "before": "Idem na",
        "after": ".",
        "accepted": [
          "poštu"
        ],
        "translation": "Idę na pocztę.",
        "section": "grammar",
        "instructionTarget": {
          "target": "Dopuni rečenicu.",
          "source": "Uzupełnij zdanie."
        }
      },
      {
        "id": "grammar-4",
        "stage": "structure",
        "type": "gap",
        "instruction": "Uzupełnij lukę.",
        "before": "Pijem",
        "after": ".",
        "accepted": [
          "vodu"
        ],
        "translation": "Piję wodę.",
        "section": "grammar",
        "instructionTarget": {
          "target": "Dopuni rečenicu.",
          "source": "Uzupełnij zdanie."
        }
      },
      {
        "id": "translation-1",
        "stage": "practice",
        "type": "translate",
        "instruction": "Przetłumacz na chorwacki.",
        "prompt": "Gdzie jest dworzec?",
        "accepted": [
          "Gdje je kolodvor?"
        ],
        "section": "translation",
        "instructionTarget": {
          "target": "Prevedi na hrvatski.",
          "source": "Przetłumacz na chorwacki."
        }
      },
      {
        "id": "translation-2",
        "stage": "practice",
        "type": "translate",
        "instruction": "Przetłumacz na chorwacki.",
        "prompt": "Chciałbym zamówić rybę.",
        "accepted": [
          "Htio bih naručiti ribu."
        ],
        "section": "translation",
        "instructionTarget": {
          "target": "Prevedi na hrvatski.",
          "source": "Przetłumacz na chorwacki."
        }
      },
      {
        "id": "translation-3",
        "stage": "practice",
        "type": "translate",
        "instruction": "Przetłumacz na chorwacki.",
        "prompt": "Wczoraj pracowałam.",
        "accepted": [
          "Jučer sam radila.",
          "Radila sam jučer."
        ],
        "section": "translation",
        "instructionTarget": {
          "target": "Prevedi na hrvatski.",
          "source": "Przetłumacz na chorwacki."
        }
      },
      {
        "id": "production",
        "stage": "dialog",
        "type": "free",
        "instruction": "Napisz 2–4 zdania o sobie.",
        "points": [
          "skąd jesteś i gdzie mieszkasz",
          "co lubisz robić",
          "co zrobisz jutro"
        ],
        "keywords": [
          {
            "any": [
              "iz",
              "živim"
            ],
            "label": "skąd jesteś / gdzie mieszkasz"
          },
          {
            "any": [
              "volim"
            ],
            "label": "co lubisz"
          },
          {
            "any": [
              "ću"
            ],
            "label": "jutro"
          }
        ],
        "minSentences": 2,
        "sample": "Iz Poljske sam i živim u Krakovu. Volim putovati. Sutra ću učiti hrvatski.",
        "section": "production",
        "instructionTarget": {
          "target": "Napiši dvije rečenice o sebi.",
          "source": "Napisz dwa zdania o sobie."
        }
      },
      {
        "id": "summary",
        "stage": "summary",
        "type": "summary",
        "title": "Wynik testu A1",
        "recap": [],
        "closing": {
          "target": "Test je završen.",
          "source": "Test jest zakończony."
        }
      }
    ]
  },
  material: {
    "sourceLessonId": "a1-40",
    "grammarFocus": "test mieszany: słuchanie, czytanie, wybór, luka, tłumaczenie, wypowiedź",
    "communicativeGoal": "Sprawdzić rozumienie i aktywne użycie materiału A1.",
    "sources": [
      "https://www.coe.int/en/web/common-European-framework-reference-languages/table-1-cefr-3.3-common-reference-levels-global-scale",
      "https://www.coe.int/en/web/common-european-framework-reference-languages/cefr-descriptors-search",
      "https://croaticum.ffzg.unizg.hr/?page_id=1106",
      "https://a1.ffzg.unizg.hr/"
    ],
    "records": [
      {
        "recordId": "A1-0703",
        "type": "lesson",
        "sequence": 0,
        "hr": "",
        "pl": "",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "",
        "acceptedAnswers": [],
        "notes": "Projekt autorski oparty na deskryptorach CEFR A1 oraz zakresie początkujących kursów Croaticum. Treści nie są kopią podręcznika.",
        "tags": [
          "curriculum",
          "cefr-a1",
          "croatian"
        ]
      },
      {
        "recordId": "A1-0704",
        "type": "vocabulary",
        "sequence": 1,
        "hr": "test",
        "pl": "test",
        "lemma": "test",
        "partOfSpeech": "noun",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "test"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A1-0705",
        "type": "vocabulary",
        "sequence": 2,
        "hr": "zadatak",
        "pl": "zadanie",
        "lemma": "zadatak",
        "partOfSpeech": "noun",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "zadatak"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A1-0706",
        "type": "vocabulary",
        "sequence": 3,
        "hr": "točno",
        "pl": "poprawnie",
        "lemma": "točno",
        "partOfSpeech": "adverb",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "točno"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A1-0707",
        "type": "vocabulary",
        "sequence": 4,
        "hr": "netočno",
        "pl": "niepoprawnie",
        "lemma": "netočno",
        "partOfSpeech": "adverb",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "netočno"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A1-0708",
        "type": "vocabulary",
        "sequence": 5,
        "hr": "odabrati",
        "pl": "wybrać",
        "lemma": "odabrati",
        "partOfSpeech": "verb",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "odabrati"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A1-0709",
        "type": "vocabulary",
        "sequence": 6,
        "hr": "napisati",
        "pl": "napisać",
        "lemma": "napisati",
        "partOfSpeech": "verb",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "napisati"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A1-0710",
        "type": "vocabulary",
        "sequence": 7,
        "hr": "poslušati",
        "pl": "posłuchać",
        "lemma": "poslušati",
        "partOfSpeech": "verb",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "poslušati"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A1-0711",
        "type": "vocabulary",
        "sequence": 8,
        "hr": "završiti",
        "pl": "zakończyć",
        "lemma": "završiti",
        "partOfSpeech": "verb",
        "exerciseType": "flashcard|recognition|production",
        "acceptedAnswers": [
          "završiti"
        ],
        "notes": "Docelowy element aktywnego słownictwa; wrzuć do FSRS po ukończeniu lekcji.",
        "tags": [
          "vocab",
          "active"
        ]
      },
      {
        "recordId": "A1-0712",
        "type": "sentence",
        "sequence": 1,
        "hr": "Pročitaj i odaberi točan odgovor.",
        "pl": "Przeczytaj i wybierz poprawną odpowiedź.",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "Pročitaj i odaberi točan odgovor."
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych warto akceptować brak części znaków diakrytycznych jako soft error, ale pokazać poprawną pisownię.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A1-0713",
        "type": "sentence",
        "sequence": 2,
        "hr": "Poslušaj kratki dijalog.",
        "pl": "Posłuchaj krótkiego dialogu.",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "Poslušaj kratki dijalog."
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych warto akceptować brak części znaków diakrytycznych jako soft error, ale pokazać poprawną pisownię.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A1-0714",
        "type": "sentence",
        "sequence": 3,
        "hr": "Napiši dvije rečenice o sebi.",
        "pl": "Napisz dwa zdania o sobie.",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "Napiši dvije rečenice o sebi."
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych warto akceptować brak części znaków diakrytycznych jako soft error, ale pokazać poprawną pisownię.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A1-0715",
        "type": "sentence",
        "sequence": 4,
        "hr": "Dopuni rečenicu.",
        "pl": "Uzupełnij zdanie.",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "Dopuni rečenicu."
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych warto akceptować brak części znaków diakrytycznych jako soft error, ale pokazać poprawną pisownię.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A1-0716",
        "type": "sentence",
        "sequence": 5,
        "hr": "Prevedi na hrvatski.",
        "pl": "Przetłumacz na chorwacki.",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "Prevedi na hrvatski."
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych warto akceptować brak części znaków diakrytycznych jako soft error, ale pokazać poprawną pisownię.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A1-0717",
        "type": "sentence",
        "sequence": 6,
        "hr": "Test je završen.",
        "pl": "Test jest zakończony.",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "translation|word_order|listening|gap",
        "acceptedAnswers": [
          "Test je završen."
        ],
        "notes": "Zdanie autorskie do ćwiczeń; przy inputach tekstowych warto akceptować brak części znaków diakrytycznych jako soft error, ale pokazać poprawną pisownię.",
        "tags": [
          "sentence",
          "production",
          "comprehension"
        ]
      },
      {
        "recordId": "A1-0718",
        "type": "exercise_blueprint",
        "sequence": 1,
        "hr": "",
        "pl": "",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "reading",
        "acceptedAnswers": [],
        "notes": "Krótki tekst A1 + 3 pytania na rozumienie.",
        "tags": [
          "exercise",
          "lesson-player"
        ]
      },
      {
        "recordId": "A1-0719",
        "type": "exercise_blueprint",
        "sequence": 2,
        "hr": "",
        "pl": "",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "listening",
        "acceptedAnswers": [],
        "notes": "Krótki dialog A1 + 3 pytania; audio może być TTS na etapie MVP.",
        "tags": [
          "exercise",
          "lesson-player"
        ]
      },
      {
        "recordId": "A1-0720",
        "type": "exercise_blueprint",
        "sequence": 3,
        "hr": "",
        "pl": "",
        "lemma": "",
        "partOfSpeech": "",
        "exerciseType": "production",
        "acceptedAnswers": [],
        "notes": "2–4 zdania samodzielnej wypowiedzi obejmujące materiał poziomu.",
        "tags": [
          "exercise",
          "lesson-player"
        ]
      }
    ]
  },
};
